from collections.abc import Callable

import optype as op

__all__ = [
    "doc_replace",
    "docformat",
    "extend_notes_in_docstring",
    "filldoc",
    "indentcount_lines",
    "inherit_docstring_from",
    "replace_notes_in_docstring",
    "unindent_dict",
    "unindent_string",
]

def docformat(docstring: str, docdict: dict[str, str] | None = None) -> str: ...
def inherit_docstring_from[FuncT: Callable[..., object]](cls: type | object) -> Callable[[FuncT], FuncT]: ...
def extend_notes_in_docstring[FuncT: Callable[..., object]](cls: type | object, notes: str) -> Callable[[FuncT], FuncT]: ...
def replace_notes_in_docstring[FuncT: Callable[..., object]](cls: type | object, notes: str) -> Callable[[FuncT], FuncT]: ...
def indentcount_lines(lines: op.CanIter[op.CanNext[str]]) -> int: ...
def filldoc[FuncT: Callable[..., object]](docdict: dict[str, str], unindent_params: bool = True) -> Callable[[FuncT], FuncT]: ...
def unindent_dict(docdict: dict[str, str]) -> dict[str, str]: ...
def unindent_string(docstring: str) -> str: ...
def doc_replace[FuncT: Callable[..., object]](obj: object, oldval: str, newval: str) -> Callable[[FuncT], FuncT]: ...
