import typing as _t

version: _t.Final[_t.LiteralString] = ...
full_version: _t.Final[_t.LiteralString] = ...
short_version: _t.Final[_t.Literal["1.16.0rc2", "1.16.0"]] = ...
git_revision: _t.Final[_t.LiteralString] = ...
release: _t.Final[bool] = ...
