changelog:
  categories:
    - title: 💥 Breaking
      labels:
        - "is: breaking"
    - title: ⏬ SciPy Changes
      labels:
        - "stubs: api change"
        - "stubs: api change - undocumented"
        - "topic: upstream release"
        - "topic: deprecation"
    - title: ✨ Improvements
      labels:
        - "is: feature"
        - "stubs: incomplete"
        - "stubs: performance"
        - "stubs: shape-typing"
        - "topic: DX"
    - title: 🐛 Fixes
      labels:
        - "is: fix"
        - "stubs: incorrect"
    - title: ↪️ Workarounds
      labels:
        - "is: workaround"
    - title: 📝 Documentation
      labels:
        - "topic: documentation"
    - title: ✅ Testing
      labels:
        - "topic: testing"
    - title: 🧹 Maintenance
      labels:
        - "is: chore"
        - "is: refactor"
        - "topic: code style"
        - "topic: dependencies"
    - title: Other Changes
      labels:
        - "*"
