# mypy reports false positive `overload-overlap` errors for `zeta`, which vary per numpy version
# mypy: disable-error-code=overload-overlap

from typing import Any, Literal as L, Never, Unpack, overload

import numpy as np
import optype as op
import optype.numpy as onp
import optype.numpy.compat as npc

from ._ufuncs import _KwBase, psi as digamma

__all__ = [
    "ai_zeros",
    "assoc_laguerre",
    "bei_zeros",
    "beip_zeros",
    "ber_zeros",
    "bernoulli",
    "berp_zeros",
    "bi_zeros",
    "comb",
    "digamma",
    "diric",
    "erf_zeros",
    "euler",
    "factorial",
    "factorial2",
    "factorialk",
    "fresnel_zeros",
    "fresnelc_zeros",
    "fresnels_zeros",
    "h1vp",
    "h2vp",
    "ivp",
    "jn_zeros",
    "jnjnp_zeros",
    "jnp_zeros",
    "jnyn_zeros",
    "jvp",
    "kei_zeros",
    "keip_zeros",
    "kelvin_zeros",
    "ker_zeros",
    "kerp_zeros",
    "kvp",
    "lmbda",
    "lqmn",
    "lqn",
    "mathieu_even_coef",
    "mathieu_odd_coef",
    "obl_cv_seq",
    "pbdn_seq",
    "pbdv_seq",
    "pbvv_seq",
    "perm",
    "polygamma",
    "pro_cv_seq",
    "riccati_jn",
    "riccati_yn",
    "sinc",
    "softplus",
    "stirling2",
    "y0_zeros",
    "y1_zeros",
    "y1p_zeros",
    "yn_zeros",
    "ynp_zeros",
    "yvp",
    "zeta",
]

###

type _ToIntOrND = onp.ToInt | onp.ToIntND
type _ToFloatOrND = onp.ToFloat | onp.ToFloatND
type _ToComplexOrND = onp.ToComplex | onp.ToComplexND
type _ToJustComplexOrND = onp.ToJustComplex | onp.ToJustComplexND

type _AsF64 = np.float64 | npc.integer64 | npc.integer32
type _ToF32 = onp.ToFloat32 | op.JustFloat | int

type _Extend0 = L["zero"]
type _ExtendC = L["complex"]
type _Extend = L[_Extend0, _ExtendC]

# ruff: file-ignore[snake-case-type-alias]
type _tuple2[T] = tuple[T, T]
type _tuple4[T0, T1] = tuple[T0, T1, T1, T1]
type _tuple8[T0, T1] = tuple[T0, T1, T1, T1, T1, T1, T1, T1]

type _i = np.int32 | np.int64

type _f8_1d = onp.Array1D[np.float64]
type _f8_2d = onp.Array2D[np.float64]
type _f8_nd = onp.ArrayND[np.float64]
type _c8_1d = onp.Array1D[np.complex128]
type _c8_2d = onp.Array2D[np.complex128]
type _c8_nd = onp.ArrayND[np.complex128]

# workaround for a strange bug in pyright's overlapping overload detection with `numpy<2.1`
type _WorkaroundForPyright = tuple[int] | tuple[Any, ...]

###

@overload
def sinc[InexactT: npc.inexact](x: InexactT) -> InexactT: ...
@overload
def sinc(x: float | onp.ToInt) -> np.float64: ...
@overload
def sinc(x: op.JustComplex) -> np.complex128: ...
@overload
def sinc(x: complex) -> np.float64 | np.complex128: ...  # type: ignore[overload-cannot-match]  # pyright: ignore[reportOverlappingOverload]
@overload
def sinc[InexactT: npc.inexact, ShapeT: tuple[int, ...]](x: onp.ArrayND[InexactT, ShapeT]) -> onp.ArrayND[InexactT, ShapeT]: ...
@overload
def sinc[InexactT: npc.inexact](x: onp.ToArrayND[Never, InexactT]) -> onp.ArrayND[InexactT, _WorkaroundForPyright]: ...
@overload
def sinc(x: onp.ToFloat64_ND) -> onp.ArrayND[np.float64]: ...
@overload
def sinc(x: onp.ToJustComplex128_ND) -> onp.ArrayND[np.complex128]: ...
@overload
def sinc(x: onp.ToComplexND) -> onp.ArrayND[Any, _WorkaroundForPyright]: ...

#
@overload
def diric(x: onp.ToFloat, n: int | _i) -> onp.Array0D[np.float64]: ...
@overload
def diric(x: onp.ToFloat, n: onp.ToInt) -> onp.Array0D[npc.floating]: ...
@overload
def diric(x: _ToFloatOrND, n: onp.ToInt) -> onp.ArrayND[npc.floating]: ...

#
def jnjnp_zeros(nt: onp.ToInt) -> _tuple4[_f8_1d, onp.Array1D[np.int32]]: ...
def jnyn_zeros(n: onp.ToInt, nt: onp.ToInt) -> _tuple4[_f8_1d, _f8_1d]: ...
def jn_zeros(n: onp.ToInt, nt: onp.ToInt) -> _f8_1d: ...
def jnp_zeros(n: onp.ToInt, nt: onp.ToInt) -> _f8_1d: ...
def yn_zeros(n: onp.ToInt, nt: onp.ToInt) -> _f8_1d: ...
def ynp_zeros(n: onp.ToInt, nt: onp.ToInt) -> _f8_1d: ...

#
def y0_zeros(nt: onp.ToInt, complex: bool = False) -> _tuple2[_c8_1d]: ...
def y1_zeros(nt: onp.ToInt, complex: bool = False) -> _tuple2[_c8_1d]: ...
def y1p_zeros(nt: onp.ToInt, complex: bool = False) -> _tuple2[_c8_1d]: ...

#
@overload
def jvp(v: onp.ToFloat, z: onp.ToFloat, n: onp.ToInt = 1) -> np.float64: ...
@overload
def jvp(v: onp.ToFloat, z: onp.ToJustComplex, n: onp.ToInt = 1) -> np.complex128: ...
@overload
def jvp(v: onp.ToFloat, z: onp.ToComplex, n: onp.ToInt = 1) -> np.float64 | np.complex128: ...
@overload
def jvp(v: _ToFloatOrND, z: onp.ToFloatND, n: onp.ToInt = 1) -> onp.ArrayND[np.float64]: ...
@overload
def jvp(v: onp.ToFloatND, z: _ToFloatOrND, n: onp.ToInt = 1) -> onp.ArrayND[np.float64]: ...
@overload
def jvp(v: _ToFloatOrND, z: onp.ToJustComplexND, n: onp.ToInt = 1) -> onp.ArrayND[np.complex128]: ...
@overload
def jvp(v: onp.ToFloatND, z: _ToJustComplexOrND, n: onp.ToInt = 1) -> onp.ArrayND[np.complex128]: ...
@overload
def jvp(v: _ToFloatOrND, z: onp.ToComplexND, n: onp.ToInt = 1) -> onp.ArrayND[np.float64 | np.complex128]: ...
@overload
def jvp(v: onp.ToFloatND, z: _ToComplexOrND, n: onp.ToInt = 1) -> onp.ArrayND[np.float64 | np.complex128]: ...

#
@overload
def yvp(v: onp.ToFloat, z: onp.ToFloat, n: onp.ToInt = 1) -> np.float64: ...
@overload
def yvp(v: onp.ToFloat, z: onp.ToJustComplex, n: onp.ToInt = 1) -> np.complex128: ...
@overload
def yvp(v: onp.ToFloat, z: onp.ToComplex, n: onp.ToInt = 1) -> np.float64 | np.complex128: ...
@overload
def yvp(v: _ToFloatOrND, z: onp.ToFloatND, n: onp.ToInt = 1) -> onp.ArrayND[np.float64]: ...
@overload
def yvp(v: onp.ToFloatND, z: _ToFloatOrND, n: onp.ToInt = 1) -> onp.ArrayND[np.float64]: ...
@overload
def yvp(v: _ToFloatOrND, z: onp.ToJustComplexND, n: onp.ToInt = 1) -> onp.ArrayND[np.complex128]: ...
@overload
def yvp(v: onp.ToFloatND, z: _ToJustComplexOrND, n: onp.ToInt = 1) -> onp.ArrayND[np.complex128]: ...
@overload
def yvp(v: _ToFloatOrND, z: onp.ToComplexND, n: onp.ToInt = 1) -> onp.ArrayND[np.float64 | np.complex128]: ...
@overload
def yvp(v: onp.ToFloatND, z: _ToComplexOrND, n: onp.ToInt = 1) -> onp.ArrayND[np.float64 | np.complex128]: ...

#
@overload
def kvp(v: onp.ToFloat, z: onp.ToFloat, n: onp.ToInt = 1) -> np.float64: ...
@overload
def kvp(v: onp.ToFloat, z: onp.ToJustComplex, n: onp.ToInt = 1) -> np.complex128: ...
@overload
def kvp(v: onp.ToFloat, z: onp.ToComplex, n: onp.ToInt = 1) -> np.float64 | np.complex128: ...
@overload
def kvp(v: _ToFloatOrND, z: onp.ToFloatND, n: onp.ToInt = 1) -> onp.ArrayND[np.float64]: ...
@overload
def kvp(v: onp.ToFloatND, z: _ToFloatOrND, n: onp.ToInt = 1) -> onp.ArrayND[np.float64]: ...
@overload
def kvp(v: _ToFloatOrND, z: onp.ToJustComplexND, n: onp.ToInt = 1) -> onp.ArrayND[np.complex128]: ...
@overload
def kvp(v: onp.ToFloatND, z: _ToJustComplexOrND, n: onp.ToInt = 1) -> onp.ArrayND[np.complex128]: ...
@overload
def kvp(v: _ToFloatOrND, z: onp.ToComplexND, n: onp.ToInt = 1) -> onp.ArrayND[np.float64 | np.complex128]: ...
@overload
def kvp(v: onp.ToFloatND, z: _ToComplexOrND, n: onp.ToInt = 1) -> onp.ArrayND[np.float64 | np.complex128]: ...

#
@overload
def ivp(v: onp.ToFloat, z: onp.ToFloat, n: onp.ToInt = 1) -> np.float64: ...
@overload
def ivp(v: onp.ToFloat, z: onp.ToJustComplex, n: onp.ToInt = 1) -> np.complex128: ...
@overload
def ivp(v: onp.ToFloat, z: onp.ToComplex, n: onp.ToInt = 1) -> np.float64 | np.complex128: ...
@overload
def ivp(v: _ToFloatOrND, z: onp.ToFloatND, n: onp.ToInt = 1) -> onp.ArrayND[np.float64]: ...
@overload
def ivp(v: onp.ToFloatND, z: _ToFloatOrND, n: onp.ToInt = 1) -> onp.ArrayND[np.float64]: ...
@overload
def ivp(v: _ToFloatOrND, z: onp.ToJustComplexND, n: onp.ToInt = 1) -> onp.ArrayND[np.complex128]: ...
@overload
def ivp(v: onp.ToFloatND, z: _ToJustComplexOrND, n: onp.ToInt = 1) -> onp.ArrayND[np.complex128]: ...
@overload
def ivp(v: _ToFloatOrND, z: onp.ToComplexND, n: onp.ToInt = 1) -> onp.ArrayND[np.float64 | np.complex128]: ...
@overload
def ivp(v: onp.ToFloatND, z: _ToComplexOrND, n: onp.ToInt = 1) -> onp.ArrayND[np.float64 | np.complex128]: ...

#
@overload
def h1vp(v: onp.ToFloat, z: onp.ToComplex, n: onp.ToInt = 1) -> np.complex128: ...
@overload
def h1vp(v: _ToFloatOrND, z: onp.ToComplexND, n: onp.ToInt = 1) -> onp.ArrayND[np.complex128]: ...
@overload
def h1vp(v: onp.ToFloatND, z: _ToComplexOrND, n: onp.ToInt = 1) -> onp.ArrayND[np.complex128]: ...

#
@overload
def h2vp(v: onp.ToFloat, z: onp.ToComplex, n: onp.ToInt = 1) -> np.complex128: ...
@overload
def h2vp(v: _ToFloatOrND, z: onp.ToComplexND, n: onp.ToInt = 1) -> onp.ArrayND[np.complex128]: ...
@overload
def h2vp(v: onp.ToFloatND, z: _ToComplexOrND, n: onp.ToInt = 1) -> onp.ArrayND[np.complex128]: ...

#
def riccati_jn(n: onp.ToInt, x: onp.ToFloat) -> _tuple2[_f8_1d]: ...
def riccati_yn(n: onp.ToInt, x: onp.ToFloat) -> _tuple2[_f8_1d]: ...

#
def erf_zeros(nt: onp.ToInt) -> _c8_1d: ...
def fresnelc_zeros(nt: onp.ToInt) -> _c8_1d: ...
def fresnels_zeros(nt: onp.ToInt) -> _c8_1d: ...
def fresnel_zeros(nt: onp.ToInt) -> _c8_1d: ...

#
@overload
def assoc_laguerre(x: onp.ToFloat, n: onp.ToInt, k: onp.ToFloat = 0.0) -> np.float64: ...
@overload
def assoc_laguerre(x: onp.ToJustComplex, n: onp.ToInt, k: onp.ToFloat = 0.0) -> np.complex128: ...
@overload
def assoc_laguerre(x: onp.ToComplex, n: onp.ToInt, k: onp.ToFloat = 0.0) -> np.float64 | np.complex128: ...
@overload
def assoc_laguerre(x: _ToFloatOrND, n: _ToIntOrND, k: onp.ToFloatND) -> onp.ArrayND[np.float64]: ...
@overload
def assoc_laguerre(x: _ToFloatOrND, n: onp.ToIntND, k: _ToFloatOrND) -> onp.ArrayND[np.float64]: ...
@overload
def assoc_laguerre(x: onp.ToFloatND, n: _ToIntOrND, k: _ToFloatOrND) -> onp.ArrayND[np.float64]: ...
@overload
def assoc_laguerre(x: _ToJustComplexOrND, n: _ToIntOrND, k: onp.ToFloatND) -> onp.ArrayND[np.complex128]: ...
@overload
def assoc_laguerre(x: _ToJustComplexOrND, n: onp.ToIntND, k: _ToFloatOrND) -> onp.ArrayND[np.complex128]: ...
@overload
def assoc_laguerre(x: onp.ToJustComplexND, n: _ToIntOrND, k: _ToFloatOrND) -> onp.ArrayND[np.complex128]: ...
@overload
def assoc_laguerre(x: _ToComplexOrND, n: _ToIntOrND, k: onp.ToFloatND) -> onp.ArrayND[np.float64 | np.complex128]: ...
@overload
def assoc_laguerre(x: _ToComplexOrND, n: onp.ToIntND, k: _ToFloatOrND) -> onp.ArrayND[np.float64 | np.complex128]: ...
@overload
def assoc_laguerre(x: onp.ToComplexND, n: _ToIntOrND, k: _ToFloatOrND) -> onp.ArrayND[np.float64 | np.complex128]: ...
@overload
def assoc_laguerre(
    x: _ToComplexOrND, n: _ToIntOrND, k: _ToFloatOrND
) -> np.float64 | np.complex128 | onp.ArrayND[np.float64 | np.complex128]: ...

#
@overload
def polygamma(n: onp.ToInt, x: onp.ToFloat) -> onp.Array0D[np.float64]: ...
@overload
def polygamma(n: _ToIntOrND, x: _ToFloatOrND) -> onp.ArrayND[np.float64]: ...

#
def mathieu_even_coef(m: onp.ToInt, q: onp.ToFloat) -> _f8_1d: ...
def mathieu_odd_coef(m: onp.ToInt, q: onp.ToFloat) -> _f8_1d: ...

#
@overload
def lqn(n: onp.ToInt, z: onp.ToFloat) -> _tuple2[_f8_1d]: ...
@overload
def lqn(n: onp.ToInt, z: _ToFloatOrND) -> _tuple2[_f8_nd]: ...
@overload
def lqn(n: onp.ToInt, z: onp.ToJustComplex) -> _tuple2[_c8_1d]: ...
@overload
def lqn(n: onp.ToInt, z: _ToJustComplexOrND) -> _tuple2[_c8_nd]: ...
@overload
def lqn(n: onp.ToInt, z: _ToComplexOrND) -> _tuple2[_f8_nd] | _tuple2[_c8_nd]: ...

#
@overload
def lqmn(m: onp.ToFloat, n: onp.ToFloat, z: onp.ToFloat) -> _tuple2[_f8_2d]: ...
@overload
def lqmn(m: onp.ToFloat, n: onp.ToFloat, z: _ToFloatOrND) -> _tuple2[_f8_nd]: ...
@overload
def lqmn(m: onp.ToFloat, n: onp.ToFloat, z: onp.ToJustComplex) -> _tuple2[_c8_2d]: ...
@overload
def lqmn(m: onp.ToFloat, n: onp.ToFloat, z: _ToJustComplexOrND) -> _tuple2[_c8_nd]: ...
@overload
def lqmn(m: onp.ToFloat, n: onp.ToFloat, z: _ToComplexOrND) -> _tuple2[_f8_nd] | _tuple2[_c8_nd]: ...

# accepts floating input, but it's probably not useful
def bernoulli(n: onp.ToFloat) -> _f8_1d: ...
def euler(n: onp.ToFloat) -> _f8_1d: ...
def ai_zeros(nt: onp.ToFloat) -> _tuple4[_f8_1d, _f8_1d]: ...
def bi_zeros(nt: onp.ToFloat) -> _tuple4[_f8_1d, _f8_1d]: ...

#
def lmbda(v: onp.ToFloat, x: onp.ToFloat) -> _tuple2[_f8_1d]: ...
def pbdv_seq(v: onp.ToFloat, x: onp.ToFloat) -> _tuple2[_f8_1d]: ...
def pbvv_seq(v: onp.ToFloat, x: onp.ToFloat) -> _tuple2[_f8_1d]: ...
def pbdn_seq(n: onp.ToInt, z: onp.ToComplex) -> _tuple2[_c8_1d]: ...

#
def ber_zeros(nt: onp.ToInt) -> _f8_1d: ...
def bei_zeros(nt: onp.ToInt) -> _f8_1d: ...
def ker_zeros(nt: onp.ToInt) -> _f8_1d: ...
def kei_zeros(nt: onp.ToInt) -> _f8_1d: ...
def berp_zeros(nt: onp.ToInt) -> _f8_1d: ...
def beip_zeros(nt: onp.ToInt) -> _f8_1d: ...
def kerp_zeros(nt: onp.ToInt) -> _f8_1d: ...
def keip_zeros(nt: onp.ToInt) -> _f8_1d: ...
def kelvin_zeros(nt: onp.ToInt) -> _tuple8[_f8_1d, _f8_1d]: ...

#
def pro_cv_seq(m: onp.ToInt, n: onp.ToInt, c: onp.ToFloat) -> _f8_1d: ...
def obl_cv_seq(m: onp.ToInt, n: onp.ToInt, c: onp.ToFloat) -> _f8_1d: ...

#
@overload
def comb(N: onp.ToInt | onp.Array0D[npc.integer], k: onp.ToInt, *, exact: onp.ToTrue, repetition: bool = False) -> int: ...
@overload
def comb(N: onp.ToFloat, k: onp.ToFloat, *, exact: onp.ToFalse = False, repetition: bool = False) -> np.float64: ...
@overload
def comb(
    N: _ToFloatOrND, k: onp.ToFloatND, *, exact: onp.ToFalse = False, repetition: bool = False
) -> onp.ArrayND[np.float64]: ...
@overload
def comb(
    N: onp.ToFloatND, k: _ToFloatOrND, *, exact: onp.ToFalse = False, repetition: bool = False
) -> onp.ArrayND[np.float64]: ...
@overload
def comb(
    N: _ToFloatOrND, k: _ToFloatOrND, *, exact: onp.ToFalse = False, repetition: bool = False
) -> np.float64 | onp.ArrayND[np.float64]: ...

#
@overload
def perm(N: onp.ToInt | onp.Array0D[npc.integer], k: onp.ToInt | onp.Array0D[npc.integer], exact: onp.ToTrue) -> int: ...
@overload
def perm(N: onp.ToFloat, k: onp.ToFloat, exact: onp.ToFalse = False) -> np.float64: ...
@overload
def perm(N: _ToFloatOrND, k: onp.ToFloatND, exact: onp.ToFalse = False) -> onp.ArrayND[np.float64]: ...
@overload
def perm(N: onp.ToFloatND, k: _ToFloatOrND, exact: onp.ToFalse = False) -> onp.ArrayND[np.float64]: ...
@overload
def perm(N: _ToFloatOrND, k: _ToFloatOrND, exact: onp.ToFalse = False) -> np.float64 | onp.ArrayND[np.float64]: ...

#
@overload  # 0d ~int, exact=True
def factorial(n: onp.ToJustInt, exact: onp.ToTrue, extend: _Extend0 = "zero") -> int: ...
@overload  # Nd +int, exact=True
def factorial(n: onp.ToIntND, exact: onp.ToTrue, extend: _Extend0 = "zero") -> onp.ArrayND[np.int_ | np.object_]: ...
@overload  # 0d +float
def factorial(n: onp.ToFloat, exact: onp.ToFalse = False, extend: _Extend = "zero") -> np.float64: ...
@overload  # Nd +float
def factorial(n: onp.ToFloatND, exact: onp.ToFalse = False, extend: _Extend = "zero") -> onp.ArrayND[np.float64]: ...
@overload  # 0d ~complex
def factorial(n: onp.ToJustComplex, exact: onp.ToFalse = False, *, extend: _ExtendC) -> np.complex128: ...
@overload  # Nd ~complex
def factorial(n: onp.ToJustComplexND, exact: onp.ToFalse = False, *, extend: _ExtendC) -> onp.ArrayND[np.complex128]: ...

#
@overload  # 0d ~int, exact=True
def factorial2(n: onp.ToJustInt, exact: onp.ToTrue, extend: _Extend0 = "zero") -> int: ...
@overload  # Nd +int, exact=True
def factorial2(n: onp.ToIntND, exact: onp.ToTrue, extend: _Extend0 = "zero") -> onp.ArrayND[np.int_ | np.object_]: ...
@overload  # 0d +float
def factorial2(n: onp.ToFloat, exact: onp.ToFalse = False, extend: _Extend = "zero") -> np.float64: ...
@overload  # Nd +float
def factorial2(n: onp.ToFloatND, exact: onp.ToFalse = False, extend: _Extend = "zero") -> onp.ArrayND[np.float64]: ...
@overload  # 0d ~complex
def factorial2(n: onp.ToJustComplex, exact: onp.ToFalse = False, *, extend: _ExtendC) -> np.complex128: ...
@overload  # Nd ~complex
def factorial2(n: onp.ToJustComplexND, exact: onp.ToFalse = False, *, extend: _ExtendC) -> onp.ArrayND[np.complex128]: ...

#
@overload  # 0d ~int, exact=True
def factorialk(n: onp.ToJustInt, k: onp.ToJustInt, exact: onp.ToTrue, extend: _Extend0 = "zero") -> int: ...
@overload  # Nd +int, exact=True
def factorialk(
    n: onp.ToIntND, k: onp.ToJustInt, exact: onp.ToTrue, extend: _Extend0 = "zero"
) -> onp.ArrayND[np.int_ | np.object_]: ...
@overload  # 0d +float
def factorialk(n: onp.ToFloat, k: onp.ToInt, exact: onp.ToFalse = False, extend: _Extend = "zero") -> np.float64: ...
@overload  # Nd +float
def factorialk(
    n: onp.ToFloatND, k: onp.ToInt, exact: onp.ToFalse = False, extend: _Extend = "zero"
) -> onp.ArrayND[np.float64]: ...
@overload  # 0d ~complex
def factorialk(n: onp.ToJustComplex, k: onp.ToInt, exact: onp.ToFalse = False, *, extend: _ExtendC) -> np.complex128: ...
@overload  # Nd ~complex
def factorialk(
    n: onp.ToJustComplexND, k: onp.ToInt, exact: onp.ToFalse = False, *, extend: _ExtendC
) -> onp.ArrayND[np.complex128]: ...

#
@overload
def stirling2(N: onp.ToInt, K: onp.ToInt, *, exact: onp.ToTrue) -> int: ...
@overload
def stirling2(N: _ToIntOrND, K: onp.ToIntND, *, exact: onp.ToTrue) -> onp.ArrayND[np.object_]: ...
@overload
def stirling2(N: onp.ToIntND, K: _ToIntOrND, *, exact: onp.ToTrue) -> onp.ArrayND[np.object_]: ...
@overload
def stirling2(N: onp.ToInt, K: onp.ToInt, *, exact: onp.ToFalse = False) -> np.float64: ...
@overload
def stirling2(N: _ToIntOrND, K: onp.ToIntND, *, exact: onp.ToFalse = False) -> _f8_nd: ...
@overload
def stirling2(N: onp.ToIntND, K: _ToIntOrND, *, exact: onp.ToFalse = False) -> _f8_nd: ...

#
@overload  # out=
def zeta[ArrayT: onp.ArrayND](x: _ToComplexOrND, q: _ToFloatOrND | None, out: ArrayT) -> ArrayT: ...
@overload  # out= (keyword)
def zeta[ArrayT: onp.ArrayND](x: _ToComplexOrND, q: _ToFloatOrND | None = None, *, out: ArrayT) -> ArrayT: ...
@overload  # ~f32
def zeta(x: npc.floating32 | npc.floating16, q: _ToF32 | None = None, out: None = None) -> np.float32: ...
@overload  # +f32
def zeta(x: npc.integer16 | npc.integer8, q: onp.ToFloat32 | int | None = None, out: None = None) -> np.float32: ...
@overload  # ~bool
def zeta(x: np.bool, q: onp.ToFloat32 | None = None, out: None = None) -> np.float32: ...
@overload  # +f64, ~f32
def zeta(x: op.JustFloat | int, q: npc.floating32 | npc.floating16, out: None = None) -> np.float32: ...
@overload  # +int, +f32
def zeta(x: int, q: npc.integer16 | npc.integer8, out: None = None) -> np.float32: ...
@overload  # ~f64
def zeta(x: _AsF64, q: onp.ToFloat | None = None, out: None = None) -> np.float64: ...
@overload  # +float, ~f64
def zeta(x: onp.ToFloat, q: _AsF64, out: None = None) -> np.float64: ...
@overload  # +f64
def zeta(x: float, q: float | None = None, out: None = None) -> np.float64: ...
@overload  # Nd T:f32|f64
def zeta[ArrayT: onp.ArrayND[np.float32] | onp.ArrayND[np.float64]](
    x: ArrayT, q: _ToF32 | None = None, out: None = None
) -> ArrayT: ...
@overload  # Nd +f64
def zeta(
    x: onp.ToArrayND[float, npc.integer64 | npc.integer32], q: _ToFloatOrND | None = None, out: None = None
) -> onp.ArrayND[np.float64]: ...
@overload  # +float, Nd +f64
def zeta(
    x: _ToFloatOrND, q: onp.ToArrayND[float, np.float64 | npc.integer64 | npc.integer32], out: None = None
) -> onp.ArrayND[np.float64]: ...
@overload  # T:c64
def zeta[ComplexT: np.complex64 | onp.ArrayND[np.complex64]](
    x: ComplexT, q: _ToF32 | None = None, out: None = None
) -> ComplexT: ...
@overload  # ~complex, ~f64
def zeta(x: onp.ToJustComplex, q: _AsF64, out: None = None) -> np.complex128: ...
@overload  # Nd ~complex, ~f64
def zeta(x: onp.ToJustComplexND, q: _AsF64, out: None = None) -> onp.ArrayND[np.complex128]: ...
@overload  # ~complex, ~f32
def zeta(x: op.JustComplex, q: npc.floating32 | npc.floating16, out: None = None) -> np.complex64: ...
@overload  # ~c128
def zeta(x: npc.complexfloating128, q: onp.ToFloat | None = None, out: None = None) -> np.complex128: ...
@overload  # ~complex, +f64
def zeta(
    x: op.JustComplex, q: float | npc.integer | np.bool | npc.floating80 | None = None, out: None = None
) -> np.complex128: ...
@overload  # Nd ~c128
def zeta(x: onp.ToJustComplex128_ND, q: _ToFloatOrND | None = None, out: None = None) -> onp.ArrayND[np.complex128]: ...
@overload  # ~complex, Nd +f64
def zeta(
    x: _ToJustComplexOrND, q: onp.ToArrayND[float, np.float64 | npc.integer64 | npc.integer32], out: None = None
) -> onp.ArrayND[np.complex128]: ...
@overload  # fallback
def zeta(x: onp.ToComplex, q: onp.ToFloat | None = None, out: None = None) -> np.float64 | Any: ...
@overload  # Nd fallback
def zeta(x: onp.ToComplexND, q: _ToFloatOrND | None = None, out: None = None) -> onp.ArrayND[np.float64 | Any]: ...
@overload  # +complex, Nd fallback
def zeta(x: onp.ToComplex, q: onp.ToFloatND, out: None = None) -> onp.ArrayND[np.float64 | Any]: ...

#
@overload  # out=
def softplus[ArrayT: onp.ArrayND](x: _ToFloatOrND, *, out: ArrayT, dtype: None = None, **kwds: Unpack[_KwBase]) -> ArrayT: ...
@overload  # +f64
def softplus(x: float | np.float64, *, out: None = None, dtype: None = None, **kwds: Unpack[_KwBase]) -> np.float64: ...
@overload  # +int
def softplus(x: int | np.bool, *, out: None = None, dtype: None = None, **kwds: Unpack[_KwBase]) -> np.float64: ...
@overload  # ~integer
def softplus(x: npc.integer, *, out: None = None, dtype: None = None, **kwds: Unpack[_KwBase]) -> np.float64 | Any: ...
@overload  # Nd +int
def softplus(
    x: onp.ToIntND, *, out: None = None, dtype: None = None, **kwds: Unpack[_KwBase]
) -> onp.ArrayND[np.float64 | Any]: ...
@overload  # T:floating
def softplus[FloatingT: npc.floating](
    x: FloatingT, *, out: None = None, dtype: onp.ToDType[FloatingT] | None = None, **kwds: Unpack[_KwBase]
) -> FloatingT: ...
@overload  # +float, dtype=T:floating
def softplus[FloatingT: npc.floating](
    x: onp.ToFloat, *, out: None, dtype: onp.ToDType[FloatingT], **kwds: Unpack[_KwBase]
) -> FloatingT: ...
@overload  # +float, dtype=
def softplus(
    x: onp.ToFloat, *, out: None, dtype: onp.AnyFloatingDType | None = None, **kwds: Unpack[_KwBase]
) -> np.float64 | Any: ...
@overload  # 1d ~f64
def softplus(
    x: onp.ToJustFloat64Strict1D, *, out: None = None, dtype: onp.AnyFloat64DType | None = None, **kwds: Unpack[_KwBase]
) -> onp.Array1D[np.float64]: ...
@overload  # 2d ~f64
def softplus(
    x: onp.ToJustFloat64Strict2D, *, out: None = None, dtype: onp.AnyFloat64DType | None = None, **kwds: Unpack[_KwBase]
) -> onp.Array2D[np.float64]: ...
@overload  # 3d ~f64
def softplus(
    x: onp.ToJustFloat64Strict3D, *, out: None = None, dtype: onp.AnyFloat64DType | None = None, **kwds: Unpack[_KwBase]
) -> onp.Array3D[np.float64]: ...
@overload  # Nd ~f64
def softplus(
    x: onp.ToJustFloat64_ND, *, out: None = None, dtype: onp.AnyFloat64DType | None = None, **kwds: Unpack[_KwBase]
) -> onp.ArrayND[np.float64]: ...
@overload  # Nd T:floating
def softplus[FloatingT: npc.floating, ShapeT: tuple[int, ...]](
    x: onp.ArrayND[FloatingT, ShapeT], *, out: None = None, dtype: onp.ToDType[FloatingT] | None = None, **kwds: Unpack[_KwBase]
) -> onp.ArrayND[FloatingT, ShapeT]: ...
@overload  # Nd +float, dtype=T:floating
def softplus[FloatingT: npc.floating](
    x: onp.ToFloatND, *, out: None = None, dtype: onp.ToDType[FloatingT], **kwds: Unpack[_KwBase]
) -> onp.ArrayND[FloatingT]: ...
@overload  # Nd +float, dtype=
def softplus(
    x: onp.ToFloatND, *, out: None, dtype: onp.AnyFloatingDType | None = None, **kwds: Unpack[_KwBase]
) -> onp.ArrayND[np.float64 | Any]: ...
