min_version = "4"
requires = ["tox-uv>=1"]
env_list = ["lint", "pyright", "mypy", "3.13", "3.12", "3.11", "3.10"]

[env_run_base]
description = "stubtest with {base_python}"
runner = "uv-venv-lock-runner"
dependency_groups = ["type"]
uv_sync_flags = ["--no-editable"]
commands = [
    [
        "stubtest",
        "--ignore-unused-allowlist",
        "--allowlist=.mypyignore",
        "--mypy-config-file=pyproject.toml",
        "--concise",
        {replace = "posargs", default = ["scipy"], extend = true},
    ],
]

[env.lint]
description = "lint"
runner = "uv-venv-lock-runner"
dependency_groups = ["lint"]
commands = [
    ["repo-review", "."],
    ["ruff", "check", "--show-fixes"],
    ["ruff", "format", "--check"],
]

[env.pyright]
description = "basedpyright"
runner = "uv-venv-lock-runner"
dependency_groups = ["type"]
commands = [["basedpyright"]]

[env.mypy]
description = "basedmypy"
runner = "uv-venv-lock-runner"
dependency_groups = ["type"]
commands = [
    [
        "mypy",
        "--tb",
        "--hide-error-context",
        "--hide-error-code-links",
        "--no-pretty",
        {replace = "posargs", default = ["."], extend = true},
    ],
]
