from collections.abc import Callable, Sequence
from typing import Any, Final, Literal, overload
from typing_extensions import deprecated

import numpy as np
import optype.numpy as onp
import optype.numpy.compat as npc

from ._expm_frechet import expm_cond, expm_frechet

__all__ = [
    "coshm",
    "cosm",
    "expm",
    "expm_cond",
    "expm_frechet",
    "fractional_matrix_power",
    "funm",
    "khatri_rao",
    "logm",
    "signm",
    "sinhm",
    "sinm",
    "sqrtm",
    "tanhm",
    "tanm",
]

###

# return type is unsafely cast to the input type
type _FuncND[InexactT: npc.inexact] = Callable[[onp.Array[Any, InexactT]], onp.ToComplexND]

type _ToPosInt = npc.unsignedinteger | Literal[0, 1, 2, 3, 4, 5, 6, 7, 8]

type _IntND = onp.ArrayND[npc.integer]
type _Float64ND = onp.ArrayND[np.float64]
type _FloatND = onp.ArrayND[npc.floating]
type _Complex128ND = onp.ArrayND[np.complex128]
type _ComplexND = onp.ArrayND[npc.complexfloating]

# workaround for Pyrefly (1.1.1) that doesn't want to assign `tuple[Any, ...]` to `T: onp.AtLeast2D`.
type _AtLeast2D_ish = tuple[int, int, *tuple[int, ...]] | tuple[Any, ...]
# workaround for Pyright (1.1.411) false positive reportIncompatibleOverload on `numpy<2.1`
type _AnyShapeOrTriviallyMaybeAlso2D = tuple[int, int] | tuple[Any, ...]

###

eps: Final[np.float64] = ...  # undocumented
feps: Final[np.float32] = ...  # undocumented
_array_precision: Final[dict[Literal["i", "l", "f", "d", "F", "D"], Literal[0, 1]]] = ...  # undocumented

def _asarray_square[InexactT: npc.inexact](A: onp.ToArray2D[InexactT]) -> onp.Array2D[InexactT]: ...  # undocumented

#
@overload
def _maybe_real[ShapeT: tuple[int, ...]](
    A: onp.ArrayND[npc.inexact], B: onp.ArrayND[npc.inexact64, ShapeT], tol: float | None = None
) -> onp.ArrayND[np.float64, ShapeT]: ...  # undocumented
@overload
def _maybe_real[ShapeT: tuple[int, ...]](
    A: onp.ArrayND[npc.inexact], B: onp.ArrayND[npc.inexact32, ShapeT], tol: float | None = None
) -> onp.ArrayND[np.float32, ShapeT]: ...  # undocumented

# NOTE: with fractional `t`, real input can have either real or complex output depending on the sign of the eigenvalues
@overload  # Nd T, +int t
def fractional_matrix_power[NumberT: npc.inexact64 | npc.inexact32 | npc.integer, ShapeT: _AtLeast2D_ish](
    A: onp.ArrayND[NumberT, ShapeT], t: _ToPosInt
) -> onp.ArrayND[NumberT, ShapeT]: ...
@overload  # Nd T@inexact, int t
def fractional_matrix_power[InexactT: npc.inexact64 | npc.inexact32, ShapeT: _AtLeast2D_ish](
    A: onp.ArrayND[InexactT, ShapeT], t: onp.ToInt
) -> onp.ArrayND[InexactT, ShapeT]: ...
@overload  # Nd ~int, int t
def fractional_matrix_power[IntT: npc.integer, ShapeT: _AtLeast2D_ish](
    A: onp.ArrayND[IntT, ShapeT], t: onp.ToInt
) -> onp.ArrayND[IntT | np.float64, ShapeT]: ...
@overload  # Nd +f64, ~float t
def fractional_matrix_power[ShapeT: _AtLeast2D_ish](
    A: onp.ArrayND[npc.floating64 | npc.floating32 | npc.integer, ShapeT], t: onp.ToJustFloat
) -> onp.ArrayND[np.float64 | np.complex128, ShapeT]: ...
@overload  # Nd c128 | c64, ~float t
def fractional_matrix_power[ShapeT: _AtLeast2D_ish](
    A: onp.ArrayND[npc.complexfloating128 | npc.complexfloating64, ShapeT], t: onp.ToJustFloat
) -> onp.ArrayND[np.complex128, ShapeT]: ...
@overload  # Nd T, +int t
@deprecated("bool, float16, longdouble, and clongdouble input will no longer be supported in SciPy 1.20")
def fractional_matrix_power[NumberT: npc.inexact80 | np.float16 | np.bool, ShapeT: _AtLeast2D_ish](
    A: onp.ArrayND[NumberT, ShapeT], t: _ToPosInt
) -> onp.ArrayND[NumberT, ShapeT]: ...
@overload  # Nd bool, int t
@deprecated("bool input will no longer be supported in SciPy 1.20")
def fractional_matrix_power[ShapeT: _AtLeast2D_ish](
    A: onp.ArrayND[np.bool, ShapeT], t: onp.ToInt
) -> onp.ArrayND[np.bool | np.float64, ShapeT]: ...
@overload  # Nd bool, ~float t
@deprecated("bool input will no longer be supported in SciPy 1.20")
def fractional_matrix_power[ShapeT: _AtLeast2D_ish](
    A: onp.ArrayND[np.bool, ShapeT], t: onp.ToJustFloat
) -> onp.ArrayND[np.float64 | np.complex128, ShapeT]: ...
@overload  # Nd float16, ~float t
@deprecated("float16 input will no longer be supported in SciPy 1.20")
def fractional_matrix_power[ShapeT: _AtLeast2D_ish](
    A: onp.ArrayND[npc.floating16, ShapeT], t: onp.ToJustFloat
) -> onp.ArrayND[np.float64 | np.complex128, ShapeT]: ...
@overload  # Nd longdouble, ~float t
@deprecated("longdouble input will no longer be supported in SciPy 1.20")
def fractional_matrix_power[ShapeT: _AtLeast2D_ish](
    A: onp.ArrayND[npc.floating80, ShapeT], t: onp.ToJustFloat
) -> onp.ArrayND[np.longdouble | np.clongdouble, ShapeT]: ...
@overload  # Nd clongdouble, ~float t
@deprecated("clongdouble input will no longer be supported in SciPy 1.20")
def fractional_matrix_power[ShapeT: _AtLeast2D_ish](
    A: onp.ArrayND[npc.complexfloating160, ShapeT], t: onp.ToJustFloat
) -> onp.ArrayND[np.clongdouble, ShapeT]: ...
@overload  # 2d +float, int t
def fractional_matrix_power(A: Sequence[Sequence[float]], t: onp.ToInt) -> onp.Array2D[np.float64]: ...
@overload  # 2d +float, ~float t
def fractional_matrix_power(A: Sequence[Sequence[float]], t: onp.ToJustFloat) -> onp.Array2D[np.float64 | np.complex128]: ...
@overload  # 2d ~complex
def fractional_matrix_power(A: Sequence[list[complex]], t: onp.ToFloat) -> onp.Array2D[np.complex128]: ...
@overload  # 3d +float, int t
def fractional_matrix_power(A: Sequence[Sequence[Sequence[float]]], t: onp.ToInt) -> onp.Array3D[np.float64]: ...
@overload  # 3d +float, ~float t
def fractional_matrix_power(
    A: Sequence[Sequence[Sequence[float]]], t: onp.ToJustFloat
) -> onp.Array3D[np.float64 | np.complex128]: ...
@overload  # 3d ~complex
def fractional_matrix_power(A: Sequence[Sequence[list[complex]]], t: onp.ToFloat) -> onp.Array3D[np.complex128]: ...
@overload  # Nd +c  (fallback)
def fractional_matrix_power(A: onp.ToComplexND, t: onp.ToFloat) -> onp.ArrayND[Any, _AnyShapeOrTriviallyMaybeAlso2D]: ...

# mypy reports two false positive `overload-overlap` errors on `numpy>=2.2` for `sqrtm`, so we're forced to ignore it module-wide
# mypy: disable-error-code="overload-overlap"

# NOTE: real input can have either real or complex output depending on the sign of the values
@overload  # Nd ~f64
def sqrtm[ShapeT: _AtLeast2D_ish](
    A: onp.ArrayND[npc.floating64 | npc.integer, ShapeT],
) -> onp.ArrayND[np.float64 | np.complex128, ShapeT]: ...
@overload  # Nd ~f32
def sqrtm[ShapeT: _AtLeast2D_ish](A: onp.ArrayND[npc.floating32, ShapeT]) -> onp.ArrayND[np.float32 | np.complex64, ShapeT]: ...
@overload  # Nd T@(c128|c64
def sqrtm[ComplexT: np.complex128 | np.complex64, ShapeT: _AtLeast2D_ish](
    A: onp.ArrayND[ComplexT, ShapeT],
) -> onp.ArrayND[ComplexT, ShapeT]: ...
@overload  # Nd bool
@deprecated("bool input will no longer be supported in SciPy 1.20")
def sqrtm[ShapeT: _AtLeast2D_ish](A: onp.ArrayND[np.bool, ShapeT]) -> onp.ArrayND[np.float64 | np.complex128, ShapeT]: ...
@overload  # Nd longdouble
@deprecated("longdouble input will no longer be supported in SciPy 1.20")
def sqrtm[ShapeT: _AtLeast2D_ish](A: onp.ArrayND[npc.floating80, ShapeT]) -> onp.ArrayND[np.float64 | np.complex128, ShapeT]: ...
@overload  # Nd float16
@deprecated("float16 input will no longer be supported in SciPy 1.20")
def sqrtm[ShapeT: _AtLeast2D_ish](A: onp.ArrayND[npc.floating16, ShapeT]) -> onp.ArrayND[np.float32 | np.complex64, ShapeT]: ...
@overload  # Nd clongdouble
@deprecated("clongdouble input will no longer be supported in SciPy 1.20")
def sqrtm[ShapeT: _AtLeast2D_ish](A: onp.ArrayND[npc.complexfloating160, ShapeT]) -> onp.ArrayND[np.complex128, ShapeT]: ...
@overload  # 2d +float
def sqrtm(A: Sequence[Sequence[float]]) -> onp.Array2D[np.float64 | np.complex128]: ...
@overload  # 2d ~complex
def sqrtm(A: Sequence[list[complex]]) -> onp.Array2D[np.complex128]: ...
@overload  # 3d +float
def sqrtm(A: Sequence[Sequence[Sequence[float]]]) -> onp.Array3D[np.float64 | np.complex128]: ...
@overload  # 3d ~complex
def sqrtm(A: Sequence[Sequence[list[complex]]]) -> onp.Array3D[np.complex128]: ...
@overload  # Nd +c  (fallback)
def sqrtm(A: onp.ToComplexND) -> onp.ArrayND[Any, _AnyShapeOrTriviallyMaybeAlso2D]: ...

# NOTE: real input can have either real or complex output depending on the sign of the values
@overload  # Nd +f64 (except f16)
def logm[ShapeT: _AtLeast2D_ish](
    A: onp.ArrayND[npc.floating64 | npc.floating32 | npc.integer | np.bool, ShapeT],
) -> onp.ArrayND[np.float64 | np.complex128, ShapeT]: ...
@overload  # Nd c128 | c64
def logm[ShapeT: _AtLeast2D_ish](
    A: onp.ArrayND[npc.complexfloating128 | npc.complexfloating64, ShapeT],
) -> onp.ArrayND[np.complex128, ShapeT]: ...
@overload  # Nd longdouble
@deprecated("longdouble input will no longer be supported in SciPy 1.20")
def logm[ShapeT: _AtLeast2D_ish](A: onp.ArrayND[npc.floating80, ShapeT]) -> onp.ArrayND[np.float64 | np.complex128, ShapeT]: ...
@overload  # Nd float16
@deprecated("float16 input will no longer be supported in SciPy 1.20")
def logm[ShapeT: _AtLeast2D_ish](A: onp.ArrayND[npc.floating16, ShapeT]) -> onp.ArrayND[np.float64 | np.complex128, ShapeT]: ...
@overload  # Nd clongdouble
@deprecated("clongdouble input will no longer be supported in SciPy 1.20")
def logm[ShapeT: _AtLeast2D_ish](A: onp.ArrayND[npc.complexfloating160, ShapeT]) -> onp.ArrayND[np.complex128, ShapeT]: ...
@overload  # 2d +float
def logm(A: Sequence[Sequence[float]]) -> onp.Array2D[np.float64 | np.complex128]: ...
@overload  # 2d ~complex
def logm(A: Sequence[list[complex]]) -> onp.Array2D[np.complex128]: ...
@overload  # 3d +float
def logm(A: Sequence[Sequence[Sequence[float]]]) -> onp.Array3D[np.float64 | np.complex128]: ...
@overload  # 3d ~complex
def logm(A: Sequence[Sequence[list[complex]]]) -> onp.Array3D[np.complex128]: ...
@overload  # Nd +c  (fallback)
def logm(A: onp.ToComplexND) -> onp.ArrayND[Any, _AnyShapeOrTriviallyMaybeAlso2D]: ...

# keep in sync with `cosm`, `sinm`, and `tanm`
@overload  # Nd ~f64
def expm[ShapeT: _AtLeast2D_ish](A: onp.ArrayND[npc.floating64 | npc.integer, ShapeT]) -> onp.ArrayND[np.float64, ShapeT]: ...
@overload  # Nd ~f32
def expm[ShapeT: _AtLeast2D_ish](A: onp.ArrayND[npc.floating32, ShapeT]) -> onp.ArrayND[np.float32, ShapeT]: ...
@overload  # Nd T@(c128|c64)
def expm[ComplexT: np.complex128 | np.complex64, ShapeT: _AtLeast2D_ish](
    A: onp.ArrayND[ComplexT, ShapeT],
) -> onp.ArrayND[ComplexT, ShapeT]: ...
@overload  # Nd bool
@deprecated("bool input will no longer be supported in SciPy 1.20")
def expm[ShapeT: _AtLeast2D_ish](A: onp.ArrayND[np.bool, ShapeT]) -> onp.ArrayND[np.float64, ShapeT]: ...
@overload  # Nd float16
@deprecated("float16 input will no longer be supported in SciPy 1.20")
def expm[ShapeT: _AtLeast2D_ish](A: onp.ArrayND[npc.floating16, ShapeT]) -> onp.ArrayND[np.float32, ShapeT]: ...
@overload  # 2d +float
def expm(A: Sequence[Sequence[float]]) -> onp.Array2D[np.float64]: ...
@overload  # 2d ~complex
def expm(A: Sequence[list[complex]]) -> onp.Array2D[np.complex128]: ...
@overload  # 3d +float
def expm(A: Sequence[Sequence[Sequence[float]]]) -> onp.Array3D[np.float64]: ...
@overload  # 3d ~complex
def expm(A: Sequence[Sequence[list[complex]]]) -> onp.Array3D[np.complex128]: ...
@overload  # Nd +c  (fallback)
def expm(A: onp.ToComplexND) -> onp.ArrayND[Any, _AnyShapeOrTriviallyMaybeAlso2D]: ...

#
def _exp_sinch[ComplexT: npc.complexfloating, ShapeT: tuple[int, ...]](
    x: onp.ArrayND[ComplexT, ShapeT],
) -> onp.ArrayND[ComplexT, ShapeT]: ...  # undocumented

# keep in sync with `expm`
@overload  # Nd ~f64
def cosm[ShapeT: _AtLeast2D_ish](A: onp.ArrayND[npc.floating64 | npc.integer, ShapeT]) -> onp.ArrayND[np.float64, ShapeT]: ...
@overload  # Nd ~f32
def cosm[ShapeT: _AtLeast2D_ish](A: onp.ArrayND[npc.floating32, ShapeT]) -> onp.ArrayND[np.float32, ShapeT]: ...
@overload  # Nd T@(c128|c64)
def cosm[ComplexT: np.complex128 | np.complex64, ShapeT: _AtLeast2D_ish](
    A: onp.ArrayND[ComplexT, ShapeT],
) -> onp.ArrayND[ComplexT, ShapeT]: ...
@overload  # Nd bool
@deprecated("bool input will no longer be supported in SciPy 1.20")
def cosm[ShapeT: _AtLeast2D_ish](A: onp.ArrayND[np.bool, ShapeT]) -> onp.ArrayND[np.float64, ShapeT]: ...
@overload  # Nd float16
@deprecated("float16 input will no longer be supported in SciPy 1.20")
def cosm[ShapeT: _AtLeast2D_ish](A: onp.ArrayND[npc.floating16, ShapeT]) -> onp.ArrayND[np.float32, ShapeT]: ...
@overload  # 2d +float
def cosm(A: Sequence[Sequence[float]]) -> onp.Array2D[np.float64]: ...
@overload  # 2d ~complex
def cosm(A: Sequence[list[complex]]) -> onp.Array2D[np.complex128]: ...
@overload  # 3d +float
def cosm(A: Sequence[Sequence[Sequence[float]]]) -> onp.Array3D[np.float64]: ...
@overload  # 3d ~complex
def cosm(A: Sequence[Sequence[list[complex]]]) -> onp.Array3D[np.complex128]: ...
@overload  # Nd +c  (fallback)
def cosm(A: onp.ToComplexND) -> onp.ArrayND[Any, _AnyShapeOrTriviallyMaybeAlso2D]: ...

# keep in sync with `expm`
@overload  # Nd ~f64
def sinm[ShapeT: _AtLeast2D_ish](A: onp.ArrayND[npc.floating64 | npc.integer, ShapeT]) -> onp.ArrayND[np.float64, ShapeT]: ...
@overload  # Nd ~f32
def sinm[ShapeT: _AtLeast2D_ish](A: onp.ArrayND[npc.floating32, ShapeT]) -> onp.ArrayND[np.float32, ShapeT]: ...
@overload  # Nd T@(c128|c64)
def sinm[ComplexT: np.complex128 | np.complex64, ShapeT: _AtLeast2D_ish](
    A: onp.ArrayND[ComplexT, ShapeT],
) -> onp.ArrayND[ComplexT, ShapeT]: ...
@overload  # Nd bool
@deprecated("bool input will no longer be supported in SciPy 1.20")
def sinm[ShapeT: _AtLeast2D_ish](A: onp.ArrayND[np.bool, ShapeT]) -> onp.ArrayND[np.float64, ShapeT]: ...
@overload  # Nd float16
@deprecated("float16 input will no longer be supported in SciPy 1.20")
def sinm[ShapeT: _AtLeast2D_ish](A: onp.ArrayND[npc.floating16, ShapeT]) -> onp.ArrayND[np.float32, ShapeT]: ...
@overload  # 2d +float
def sinm(A: Sequence[Sequence[float]]) -> onp.Array2D[np.float64]: ...
@overload  # 2d ~complex
def sinm(A: Sequence[list[complex]]) -> onp.Array2D[np.complex128]: ...
@overload  # 3d +float
def sinm(A: Sequence[Sequence[Sequence[float]]]) -> onp.Array3D[np.float64]: ...
@overload  # 3d ~complex
def sinm(A: Sequence[Sequence[list[complex]]]) -> onp.Array3D[np.complex128]: ...
@overload  # Nd +c  (fallback)
def sinm(A: onp.ToComplexND) -> onp.ArrayND[Any, _AnyShapeOrTriviallyMaybeAlso2D]: ...

# keep in sync with `expm`
@overload  # Nd ~f64
def tanm[ShapeT: _AtLeast2D_ish](A: onp.ArrayND[npc.floating64 | npc.integer, ShapeT]) -> onp.ArrayND[np.float64, ShapeT]: ...
@overload  # Nd ~f32
def tanm[ShapeT: _AtLeast2D_ish](A: onp.ArrayND[npc.floating32, ShapeT]) -> onp.ArrayND[np.float32, ShapeT]: ...
@overload  # Nd T@(c128|c64)
def tanm[ComplexT: np.complex128 | np.complex64, ShapeT: _AtLeast2D_ish](
    A: onp.ArrayND[ComplexT, ShapeT],
) -> onp.ArrayND[ComplexT, ShapeT]: ...
@overload  # Nd bool
@deprecated("bool input will no longer be supported in SciPy 1.20")
def tanm[ShapeT: _AtLeast2D_ish](A: onp.ArrayND[np.bool, ShapeT]) -> onp.ArrayND[np.float64, ShapeT]: ...
@overload  # Nd float16
@deprecated("float16 input will no longer be supported in SciPy 1.20")
def tanm[ShapeT: _AtLeast2D_ish](A: onp.ArrayND[npc.floating16, ShapeT]) -> onp.ArrayND[np.float32, ShapeT]: ...
@overload  # 2d +float
def tanm(A: Sequence[Sequence[float]]) -> onp.Array2D[np.float64]: ...
@overload  # 2d ~complex
def tanm(A: Sequence[list[complex]]) -> onp.Array2D[np.complex128]: ...
@overload  # 3d +float
def tanm(A: Sequence[Sequence[Sequence[float]]]) -> onp.Array3D[np.float64]: ...
@overload  # 3d ~complex
def tanm(A: Sequence[Sequence[list[complex]]]) -> onp.Array3D[np.complex128]: ...
@overload  # Nd +c  (fallback)
def tanm(A: onp.ToComplexND) -> onp.ArrayND[Any, _AnyShapeOrTriviallyMaybeAlso2D]: ...

# keep in sync with `sinhm` and `tanhm` (and `expm`, minus the `bool` overload)
@overload  # Nd ~f64
def coshm[ShapeT: _AtLeast2D_ish](A: onp.ArrayND[npc.floating64 | npc.integer, ShapeT]) -> onp.ArrayND[np.float64, ShapeT]: ...
@overload  # Nd ~f32
def coshm[ShapeT: _AtLeast2D_ish](A: onp.ArrayND[npc.floating32, ShapeT]) -> onp.ArrayND[np.float32, ShapeT]: ...
@overload  # Nd T@(c128|c64)
def coshm[ComplexT: np.complex128 | np.complex64, ShapeT: _AtLeast2D_ish](
    A: onp.ArrayND[ComplexT, ShapeT],
) -> onp.ArrayND[ComplexT, ShapeT]: ...
@overload  # Nd float16
@deprecated("float16 input will no longer be supported in SciPy 1.20")
def coshm[ShapeT: _AtLeast2D_ish](A: onp.ArrayND[npc.floating16, ShapeT]) -> onp.ArrayND[np.float32, ShapeT]: ...
@overload  # 2d +float
def coshm(A: Sequence[Sequence[float]]) -> onp.Array2D[np.float64]: ...
@overload  # 2d ~complex
def coshm(A: Sequence[list[complex]]) -> onp.Array2D[np.complex128]: ...
@overload  # 3d +float
def coshm(A: Sequence[Sequence[Sequence[float]]]) -> onp.Array3D[np.float64]: ...
@overload  # 3d ~complex
def coshm(A: Sequence[Sequence[list[complex]]]) -> onp.Array3D[np.complex128]: ...
@overload  # Nd +c  (fallback)
def coshm(A: onp.ToComplexND) -> onp.ArrayND[Any, _AnyShapeOrTriviallyMaybeAlso2D]: ...

# keep in sync with `coshm`
@overload  # Nd ~f64
def sinhm[ShapeT: _AtLeast2D_ish](A: onp.ArrayND[npc.floating64 | npc.integer, ShapeT]) -> onp.ArrayND[np.float64, ShapeT]: ...
@overload  # Nd ~f32
def sinhm[ShapeT: _AtLeast2D_ish](A: onp.ArrayND[npc.floating32, ShapeT]) -> onp.ArrayND[np.float32, ShapeT]: ...
@overload  # Nd T@(c128|c64)
def sinhm[ComplexT: np.complex128 | np.complex64, ShapeT: _AtLeast2D_ish](
    A: onp.ArrayND[ComplexT, ShapeT],
) -> onp.ArrayND[ComplexT, ShapeT]: ...
@overload  # Nd float16
@deprecated("float16 input will no longer be supported in SciPy 1.20")
def sinhm[ShapeT: _AtLeast2D_ish](A: onp.ArrayND[npc.floating16, ShapeT]) -> onp.ArrayND[np.float32, ShapeT]: ...
@overload  # 2d +float
def sinhm(A: Sequence[Sequence[float]]) -> onp.Array2D[np.float64]: ...
@overload  # 2d ~complex
def sinhm(A: Sequence[list[complex]]) -> onp.Array2D[np.complex128]: ...
@overload  # 3d +float
def sinhm(A: Sequence[Sequence[Sequence[float]]]) -> onp.Array3D[np.float64]: ...
@overload  # 3d ~complex
def sinhm(A: Sequence[Sequence[list[complex]]]) -> onp.Array3D[np.complex128]: ...
@overload  # Nd +c  (fallback)
def sinhm(A: onp.ToComplexND) -> onp.ArrayND[Any, _AnyShapeOrTriviallyMaybeAlso2D]: ...

# keep in sync with `coshm`
@overload  # Nd ~f64
def tanhm[ShapeT: _AtLeast2D_ish](A: onp.ArrayND[npc.floating64 | npc.integer, ShapeT]) -> onp.ArrayND[np.float64, ShapeT]: ...
@overload  # Nd ~f32
def tanhm[ShapeT: _AtLeast2D_ish](A: onp.ArrayND[npc.floating32, ShapeT]) -> onp.ArrayND[np.float32, ShapeT]: ...
@overload  # Nd T@(c128|c64)
def tanhm[ComplexT: np.complex128 | np.complex64, ShapeT: _AtLeast2D_ish](
    A: onp.ArrayND[ComplexT, ShapeT],
) -> onp.ArrayND[ComplexT, ShapeT]: ...
@overload  # Nd float16
@deprecated("float16 input will no longer be supported in SciPy 1.20")
def tanhm[ShapeT: _AtLeast2D_ish](A: onp.ArrayND[npc.floating16, ShapeT]) -> onp.ArrayND[np.float32, ShapeT]: ...
@overload  # 2d +float
def tanhm(A: Sequence[Sequence[float]]) -> onp.Array2D[np.float64]: ...
@overload  # 2d ~complex
def tanhm(A: Sequence[list[complex]]) -> onp.Array2D[np.complex128]: ...
@overload  # 3d +float
def tanhm(A: Sequence[Sequence[Sequence[float]]]) -> onp.Array3D[np.float64]: ...
@overload  # 3d ~complex
def tanhm(A: Sequence[Sequence[list[complex]]]) -> onp.Array3D[np.complex128]: ...
@overload  # Nd +c  (fallback)
def tanhm(A: onp.ToComplexND) -> onp.ArrayND[Any, _AnyShapeOrTriviallyMaybeAlso2D]: ...

#
@overload  # +float64, disp: True = ...
def funm(A: onp.ToFloat64_ND, func: _FuncND[np.float64], disp: onp.ToTrue = True) -> _Float64ND: ...
@overload  # +floating, disp: False
def funm(A: onp.ToFloat64_ND, func: _FuncND[np.float64], disp: onp.ToFalse) -> tuple[_Float64ND, float]: ...
@overload  # +complexfloating, disp: True = ...
def funm(A: onp.ToJustComplex128_ND, func: _FuncND[np.complex128], disp: onp.ToTrue = True) -> _Complex128ND: ...
@overload  # +complexfloating, disp: False
def funm(A: onp.ToJustComplex128_ND, func: _FuncND[np.complex128], disp: onp.ToFalse) -> tuple[_Complex128ND, float]: ...
@overload  # T: inexact, disp: True = ...
def funm[InexactT: npc.inexact](
    A: onp.CanArrayND[InexactT], func: _FuncND[InexactT], disp: onp.ToTrue = True
) -> onp.ArrayND[InexactT]: ...
@overload  # T: inexact, disp: False
def funm[InexactT: npc.inexact](
    A: onp.CanArrayND[InexactT], func: _FuncND[InexactT], disp: onp.ToFalse
) -> tuple[onp.ArrayND[InexactT], float]: ...

# NOTE: at runtime the out dtype is value-dependent, which we ignore here, because it seems to be unintentional.
# https://github.com/scipy/scipy/issues/25657
@overload  # Nd ~f64
def signm[ShapeT: _AtLeast2D_ish](A: onp.ArrayND[npc.floating64 | npc.integer, ShapeT]) -> onp.ArrayND[np.float64, ShapeT]: ...
@overload  # Nd ~f32 | bool
def signm[ShapeT: _AtLeast2D_ish](A: onp.ArrayND[npc.floating32 | np.bool, ShapeT]) -> onp.ArrayND[np.float32, ShapeT]: ...
@overload  # Nd T@(c128|c64)
def signm[ComplexT: np.complex128 | np.complex64, ShapeT: _AtLeast2D_ish](
    A: onp.ArrayND[ComplexT, ShapeT],
) -> onp.ArrayND[ComplexT, ShapeT]: ...
@overload  # Nd longdouble
@deprecated("longdouble input will no longer be supported in SciPy 1.20")
def signm[ShapeT: _AtLeast2D_ish](A: onp.ArrayND[npc.floating80, ShapeT]) -> onp.ArrayND[np.float64, ShapeT]: ...
@overload  # Nd float16
@deprecated("float16 input will no longer be supported in SciPy 1.20")
def signm[ShapeT: _AtLeast2D_ish](A: onp.ArrayND[npc.floating16, ShapeT]) -> onp.ArrayND[np.float32, ShapeT]: ...
@overload  # Nd clongdouble
@deprecated("clongdouble input will no longer be supported in SciPy 1.20")
def signm[ShapeT: _AtLeast2D_ish](A: onp.ArrayND[npc.complexfloating160, ShapeT]) -> onp.ArrayND[np.complex128, ShapeT]: ...
@overload  # 2d +float
def signm(A: Sequence[Sequence[float]]) -> onp.Array2D[np.float64]: ...
@overload  # 2d ~complex
def signm(A: Sequence[list[complex]]) -> onp.Array2D[np.complex128]: ...
@overload  # 3d +float
def signm(A: Sequence[Sequence[Sequence[float]]]) -> onp.Array3D[np.float64]: ...
@overload  # 3d ~complex
def signm(A: Sequence[Sequence[list[complex]]]) -> onp.Array3D[np.complex128]: ...
@overload  # Nd +c  (fallback)
def signm(A: onp.ToComplexND) -> onp.ArrayND[Any, _AnyShapeOrTriviallyMaybeAlso2D]: ...

#
@overload  # +integer | ~float64
def khatri_rao(a: onp.ToIntND, b: onp.ToIntND) -> _IntND: ...
@overload  # +float64, ~float64
def khatri_rao(a: onp.ToFloat64_ND, b: onp.ToJustFloat64_ND) -> _Float64ND: ...
@overload  # ~float64, +float64
def khatri_rao(a: onp.ToJustFloat64_ND, b: onp.ToFloat64_ND) -> _Float64ND: ...
@overload  # +floating, ~floating
def khatri_rao(a: onp.ToFloatND, b: onp.ToJustFloatND) -> _FloatND: ...
@overload  # ~floating, +floating
def khatri_rao(a: onp.ToJustFloatND, b: onp.ToFloatND) -> _FloatND: ...
@overload  # +complex128, ~complex128
def khatri_rao(a: onp.ToComplex128_ND, b: onp.ToJustComplex128_ND) -> _Complex128ND: ...
@overload  # ~complex128, +complex128
def khatri_rao(a: onp.ToJustComplex128_ND, b: onp.ToComplex128_ND) -> _Complex128ND: ...
@overload  # +complexfloating, ~complexfloating
def khatri_rao(a: onp.ToComplexND, b: onp.ToJustComplexND) -> _ComplexND: ...
@overload  # ~complexfloating, +complexfloating
def khatri_rao(a: onp.ToJustComplexND, b: onp.ToComplexND) -> _ComplexND: ...
@overload  # fallback
def khatri_rao(a: onp.ToComplexND, b: onp.ToComplexND) -> onp.ArrayND[Any]: ...
