# mypy: disable-error-code="misc"

from collections.abc import Callable, Iterator, Sequence
from types import GenericAlias
from typing import Any, ClassVar, Final, Generic, Literal as L, Never, Protocol, Self, SupportsIndex, overload, type_check_only
from typing_extensions import TypeIs, TypeVar

import numpy as np
import numpy.typing as npt
import optype as op
import optype.numpy as onp
import optype.numpy.compat as npc

from ._bsr import bsr_array, bsr_matrix
from ._coo import coo_array, coo_matrix
from ._csc import csc_array, csc_matrix
from ._csr import csr_array, csr_matrix
from ._dia import dia_array, dia_matrix
from ._dok import dok_array, dok_matrix
from ._lil import lil_array, lil_matrix
from ._matrix import spmatrix as spmatrix
from ._typing import _CanAsAny, _Format
from scipy._lib._sparse import SparseABC, issparse

__all__ = ["SparseEfficiencyWarning", "SparseWarning", "issparse", "isspmatrix", "sparray"]

###

type _1D = tuple[int]  # ruff: ignore[snake-case-type-alias]
type _2D = tuple[int, int]  # ruff: ignore[snake-case-type-alias]

type _ToInt8 = np.bool | np.int8
type _ToInt16 = np.bool | npc.integer8 | npc.integer16
type _ToInt = npc.integer | np.bool
type _ToFloat32 = np.float32 | _ToInt
type _ToFloat = npc.floating | _ToInt
type _ToComplex64 = np.complex64 | _ToFloat
type _Scalar = npc.number | np.bool

type _ToSparseSeq[T] = Sequence[Sequence[T]] | Sequence[T]
type _ToSparseArray[ST: _Scalar] = onp.CanArrayND[ST] | _ToSparseSeq[ST]

type _SpMatrix[ST: _Scalar] = (
    bsr_matrix[ST] | coo_matrix[ST] | csc_matrix[ST] | csr_matrix[ST] | dia_matrix[ST] | dok_matrix[ST] | lil_matrix[ST]
)
type _SpMatrixOut[ST: _Scalar] = bsr_matrix[ST] | csc_matrix[ST] | csr_matrix[ST]

type _SpArray1D[ST: _Scalar] = coo_array[ST, _1D] | csr_array[ST, _1D] | dok_array[ST, _1D]
type _SpArray2D[ST: _Scalar] = (
    bsr_array[ST] | coo_array[ST, _2D] | csc_array[ST] | csr_array[ST, _2D] | dia_array[ST] | dok_array[ST, _2D] | lil_array[ST]
)

type _SpArrayOut[ST: _Scalar] = bsr_array[ST] | csc_array[ST] | csr_array[ST]

type _ToCSRArray[ST: _Scalar] = coo_array[ST] | csr_array[ST] | dia_array[ST] | dok_array[ST]
type _ToCSRMatrix[ST: _Scalar] = coo_matrix[ST] | csr_matrix[ST] | dia_matrix[ST] | dok_matrix[ST]

type _SparseLike[T, ST: _Scalar] = T | ST | _spbase[ST]
type _To2D[T, ST: _Scalar] = Sequence[Sequence[T | ST] | onp.CanArrayND[ST]] | onp.CanArrayND[ST]
type _To2DLike[T, ST: _Scalar] = Sequence[T | ST] | _To2D[T, ST]

type _BinOp = Callable[[object, object], Any]

type _Casting = L["no", "equiv", "safe", "same_kind", "unsafe"]

type _StackedSparseArray[ST: _Scalar] = coo_array[ST, _2D] | csc_array[ST] | csr_array[ST, _2D]

_T_co = TypeVar("_T_co", covariant=True)
_ScalarT_co = TypeVar("_ScalarT_co", bound=_Scalar, default=Any, covariant=True)
_ShapeT_co = TypeVar("_ShapeT_co", bound=tuple[int, *tuple[int, ...]], default=tuple[Any, ...], covariant=True)

_IntT = TypeVar("_IntT", bound=npc.integer, default=np.int_)
_FloatT = TypeVar("_FloatT", bound=npc.floating, default=np.float64)
_Float64T = TypeVar("_Float64T", bound=np.float64 | npc.floating80, default=np.float64)
_ComplexT = TypeVar("_ComplexT", bound=npc.complexfloating, default=np.complex128)
_Complex64T = TypeVar("_Complex64T", bound=npc.complexfloating, default=np.complex64)
_Complex128T = TypeVar("_Complex128T", bound=np.complex128 | npc.complexfloating160, default=np.complex128)

# Used to emulate `@property` overloading in `_spbase.T`
@type_check_only
class _CanTranspose(Protocol[_T_co]):
    def transpose(self, /) -> _T_co: ...

###

_formats: Final[dict[str, list[int | str]]] = ...  # undocumented
_ufuncs_with_fixed_point_at_zero: Final[frozenset[np.ufunc]] = ...  # undocumented

MAXPRINT: Final = 50  # undocumented

op_neg: Final[dict[_BinOp, _BinOp]] = ...  # undocumented
op_sym: Final[dict[_BinOp, str]] = ...  # undocumented

class SparseWarning(Warning): ...
class SparseFormatWarning(SparseWarning): ...
class SparseEfficiencyWarning(SparseWarning): ...

class _spbase(SparseABC, Generic[_ScalarT_co, _ShapeT_co]):
    __array_priority__: ClassVar[float] = 10.1
    _format: ClassVar[str] = "und"
    _allow_nd: ClassVar[Sequence[int]] = (2,)  # will be either a `tuple[int, ...]` or a `builtins.range` instance

    maxprint: Final[int | None]

    # NOTE: These `__assoc_*__` methods do not exist at runtime!
    # We use it to emulate polymorphic associated types, which allows functions such as `hstack` and `block_array` to accurately
    # annotate their return types.
    # Overloads cannot be used due to limitations in the constraint matching algorithms of the supported static type checkers.
    @type_check_only  # same kind, same scalar-type, 2d shape-type
    def __assoc_stacked__(self, /) -> _spbase[_ScalarT_co, _2D]: ...
    @type_check_only  # same kind, mapped scalar-type, 2d shape-type
    def __assoc_stacked_as__[ST: _Scalar](self, sctype: ST, /) -> _spbase[ST, _2D]: ...
    @type_check_only  # same kind, `Any` scalar-type, same shape-type  (mypy (2.2.0) can't deal with generic sctype)
    def __assoc_as_any__(self, /) -> _spbase[Any, _ShapeT_co]: ...

    #
    @property
    def ndim(self, /) -> int: ...
    @property
    def shape(self, /) -> _ShapeT_co: ...
    @property
    def nnz(self, /) -> int: ...
    @property
    def size(self, /) -> int: ...

    # abstract-ish
    @property
    def format(self, /) -> _Format: ...

    #
    @property
    def real(self, /) -> Self: ...
    @property
    def imag(self, /) -> Self: ...

    #
    @overload  # shape
    def __init__(
        self: _spbase[np.float64], /, arg1: tuple[SupportsIndex, *tuple[SupportsIndex, ...]], *, maxprint: int | None = None
    ) -> None: ...
    @overload  # sparse
    def __init__(self, /, arg1: _spbase[_ScalarT_co], *, maxprint: int | None = None) -> None: ...
    @overload  # dense array-like
    def __init__(self, /, arg1: _ToSparseArray[_ScalarT_co], *, maxprint: int | None = None) -> None: ...
    @overload  # dense array-like bool
    def __init__(self: _spbase[np.bool], /, arg1: _ToSparseSeq[bool], *, maxprint: int | None = None) -> None: ...
    @overload  # dense array-like int
    def __init__(self: _spbase[np.int_], /, arg1: _ToSparseSeq[op.JustInt], *, maxprint: int | None = None) -> None: ...
    @overload  # dense array-like float
    def __init__(self: _spbase[np.float64], /, arg1: _ToSparseSeq[op.JustFloat], *, maxprint: int | None = None) -> None: ...
    @overload  # dense array-like cfloat
    def __init__(self: _spbase[np.complex128], /, arg1: _ToSparseSeq[op.JustComplex], *, maxprint: int | None = None) -> None: ...

    #
    def __bool__(self, /) -> bool: ...

    # only `dok_*` doesn't raise `TypeError` when passed to `len`
    def __len__(self: dok_array | dok_matrix, /) -> int: ...  # pyright: ignore[reportGeneralTypeIssues]

    #
    @overload  # 1-d {csr,dok}_array
    def __iter__[ST: _Scalar](self: csr_array[ST, _1D] | dok_array[ST, _1D], /) -> Iterator[ST]: ...
    @overload  # 2-d {csc,csr}_array
    def __iter__[ST: _Scalar](self: csc_array[ST] | csr_array[ST, _2D], /) -> Iterator[csr_array[ST, _1D]]: ...
    @overload  # lil_array
    def __iter__[ST: _Scalar](self: lil_array[ST], /) -> Iterator[coo_array[ST, _1D]]: ...
    @overload  # {csc,csr}_matrix
    def __iter__[ST: _Scalar](self: csc_matrix[ST] | csr_matrix[ST], /) -> Iterator[csr_matrix[ST]]: ...
    @overload  # dok_matrix
    def __iter__[ST: _Scalar](self: dok_matrix[ST], /) -> Iterator[dok_matrix[ST]]: ...
    @overload  # lil_matrix
    def __iter__[ST: _Scalar](self: lil_matrix[ST], /) -> Iterator[lil_matrix[ST]]: ...

    #
    @overload
    def __lt__[SpBoolT: _spbase[np.bool]](self: SpBoolT, other: _spbase[_ToFloat, _ShapeT_co] | onp.ToFloat, /) -> SpBoolT: ...
    @overload
    def __lt__(self: _SpArray2D[Any], other: _spbase[_ToFloat, _2D] | onp.ToFloat, /) -> csr_array[np.bool, _2D]: ...
    @overload
    def __lt__(self: _SpArray1D[Any], other: _spbase[_ToFloat, _1D] | onp.ToFloat, /) -> csr_array[np.bool, _1D]: ...
    @overload
    def __lt__(self: spmatrix, other: _spbase[_ToFloat], /) -> csr_matrix[np.bool]: ...
    #
    @overload
    def __gt__[SpBoolT: _spbase[np.bool]](self: SpBoolT, other: _spbase[_ToFloat, _ShapeT_co] | onp.ToFloat, /) -> SpBoolT: ...
    @overload
    def __gt__(self: _SpArray2D[Any], other: _spbase[_ToFloat, _2D] | onp.ToFloat, /) -> csr_array[np.bool, _2D]: ...
    @overload
    def __gt__(self: _SpArray1D[Any], other: _spbase[_ToFloat, _1D] | onp.ToFloat, /) -> csr_array[np.bool, _1D]: ...
    @overload
    def __gt__(self: spmatrix, other: _spbase[_ToFloat], /) -> csr_matrix[np.bool]: ...
    #
    @overload
    def __le__[SpBoolT: _spbase[np.bool]](self: SpBoolT, other: _spbase[_ToFloat, _ShapeT_co] | onp.ToFloat, /) -> SpBoolT: ...
    @overload
    def __le__(self: _SpArray2D[Any], other: _spbase[_ToFloat, _2D] | onp.ToFloat, /) -> csr_array[np.bool, _2D]: ...
    @overload
    def __le__(self: _SpArray1D[Any], other: _spbase[_ToFloat, _1D] | onp.ToFloat, /) -> csr_array[np.bool, _1D]: ...
    @overload
    def __le__(self: spmatrix, other: _spbase[_ToFloat], /) -> csr_matrix[np.bool]: ...
    #
    @overload
    def __ge__[SpBoolT: _spbase[np.bool]](self: SpBoolT, other: _spbase[_ToFloat, _ShapeT_co] | onp.ToFloat, /) -> SpBoolT: ...
    @overload
    def __ge__(self: _SpArray2D[Any], other: _spbase[_ToFloat, _2D] | onp.ToFloat, /) -> csr_array[np.bool, _2D]: ...
    @overload
    def __ge__(self: _SpArray1D[Any], other: _spbase[_ToFloat, _1D] | onp.ToFloat, /) -> csr_array[np.bool, _1D]: ...
    @overload
    def __ge__(self: spmatrix, other: _spbase[_ToFloat], /) -> _SpMatrixOut[np.bool]: ...

    #
    def __neg__(self, /) -> Self: ...
    def __abs__(self, /) -> Self: ...
    def __round__(self, /, ndigits: int = 0) -> Self: ...

    #
    @overload  # `0` or sparse of same dtype
    def __add__(self, other: onp.ToFalse | _spbase[_ScalarT_co], /) -> Self: ...
    @overload  # sparse[-Int], sparse[+Int8]
    def __add__[SpNumberT: _spbase[npc.number]](self: SpNumberT, other: _spbase[_ToInt8], /) -> SpNumberT: ...
    @overload  # sparse[-Float], sparse[+Float32]
    def __add__[SpInexactT: _spbase[npc.inexact]](self: SpInexactT, other: _spbase[_ToFloat32], /) -> SpInexactT: ...
    @overload  # sparse[-Complex], sparse[+Complex64]
    def __add__[SpComplexT: _spbase[npc.complexfloating]](self: SpComplexT, other: _spbase[_ToComplex64], /) -> SpComplexT: ...
    @overload  # sparse[?], sparse[?]
    def __add__[OutT: _spbase[Any, Any]](self: _CanAsAny[OutT], other: _spbase[Any], /) -> OutT: ...
    @overload  # spmatrix[-Int], array[+Int8]
    def __add__[ST: npc.number](self: spmatrix[ST], other: onp.ArrayND[_ToInt8], /) -> onp.Matrix[ST]: ...
    @overload  # spmatrix[-Float], array[+Float32]
    def __add__[ST: npc.inexact](self: spmatrix[ST], other: onp.ArrayND[_ToFloat32], /) -> onp.Matrix[ST]: ...
    @overload  # spmatrix[-Complex], array[+Complex64]
    def __add__[ST: npc.complexfloating](self: spmatrix[ST], other: onp.ArrayND[_ToComplex64], /) -> onp.Matrix[ST]: ...
    @overload  # sparse[-Int], array[+Int8]
    def __add__[ST: npc.number, ShapeT: tuple[Any, ...]](
        self: _spbase[ST, ShapeT], other: onp.ArrayND[_ToInt8], /
    ) -> onp.ArrayND[ST, ShapeT]: ...
    @overload  # sparse[-Float], array[+Float32]
    def __add__[ST: npc.inexact, ShapeT: tuple[Any, ...]](
        self: _spbase[ST, ShapeT], other: onp.ArrayND[_ToFloat32], /
    ) -> onp.ArrayND[ST, ShapeT]: ...
    @overload  # sparse[-Complex], array[+Complex64]
    def __add__[ST: npc.complexfloating, ShapeT: tuple[Any, ...]](
        self: _spbase[ST, ShapeT], other: onp.ArrayND[_ToComplex64], /
    ) -> onp.ArrayND[ST, ShapeT]: ...
    @overload  # sparse[?], array[?]
    def __add__(self, other: onp.ArrayND[_Scalar], /) -> onp.ArrayND[Any, _ShapeT_co]: ...

    #
    @overload  # `0` or sparse of same dtype
    def __sub__(self, other: onp.ToFalse | _spbase[_ScalarT_co], /) -> Self: ...
    @overload  # sparse[-Int], sparse[+Int8]
    def __sub__[SpNumberT: _spbase[npc.number]](self: SpNumberT, other: _spbase[_ToInt8], /) -> SpNumberT: ...
    @overload  # sparse[-Float], sparse[+Float32]
    def __sub__[SpInexactT: _spbase[npc.inexact]](self: SpInexactT, other: _spbase[_ToFloat32], /) -> SpInexactT: ...
    @overload  # sparse[-Complex], sparse[+Complex64]
    def __sub__[SpComplexT: _spbase[npc.complexfloating]](self: SpComplexT, other: _spbase[_ToComplex64], /) -> SpComplexT: ...
    @overload  # sparse[?], sparse[?]
    def __sub__[OutT: _spbase[Any, Any]](self: _CanAsAny[OutT], other: _spbase[Any], /) -> OutT: ...
    @overload  # spmatrix[-Int], array[+Int8]
    def __sub__[ST: npc.number](self: spmatrix[ST], other: onp.ArrayND[_ToInt8], /) -> onp.Matrix[ST]: ...
    @overload  # spmatrix[-Float], array[+Float32]
    def __sub__[ST: npc.inexact](self: spmatrix[ST], other: onp.ArrayND[_ToFloat32], /) -> onp.Matrix[ST]: ...
    @overload  # spmatrix[-Complex], array[+Complex64]
    def __sub__[ST: npc.complexfloating](self: spmatrix[ST], other: onp.ArrayND[_ToComplex64], /) -> onp.Matrix[ST]: ...
    @overload  # sparse[-Int], array[+Int8]
    def __sub__[ST: npc.number, ShapeT: tuple[Any, ...]](
        self: _spbase[ST, ShapeT], other: onp.ArrayND[_ToInt8], /
    ) -> onp.ArrayND[ST, ShapeT]: ...
    @overload  # sparse[-Float], array[+Float32]
    def __sub__[ST: npc.inexact, ShapeT: tuple[Any, ...]](
        self: _spbase[ST, ShapeT], other: onp.ArrayND[_ToFloat32], /
    ) -> onp.ArrayND[ST, ShapeT]: ...
    @overload  # sparse[-Complex], array[+Complex64]
    def __sub__[ST: _Scalar, ShapeT: tuple[Any, ...]](
        self: _spbase[ST, ShapeT], other: onp.ArrayND[_ToComplex64], /
    ) -> onp.ArrayND[ST, ShapeT]: ...
    @overload  # sparse[?], array[?]
    def __sub__(self, other: onp.ArrayND[_Scalar], /) -> onp.ArrayND[Any, _ShapeT_co]: ...

    # NOTE: keep in sync with `__rmul__` and `multiply`
    @overload  # Self[-Bool], /, other: scalar-like +Bool
    def __mul__(self, /, other: bool | np.bool) -> Self: ...
    @overload  # Self[-Int], /, other: scalar-like +Int
    def __mul__[SelfT: _spbase[npc.number]](self: SelfT, /, other: onp.ToInt) -> SelfT: ...
    @overload  # Self[-Float], /, other: scalar-like +Float
    def __mul__[SelfT: _spbase[npc.inexact]](self: SelfT, /, other: onp.ToFloat) -> SelfT: ...
    @overload  # Self[-Complex], /, other: scalar-like +Complex
    def __mul__[SelfT: _spbase[npc.complexfloating]](self: SelfT, /, other: onp.ToComplex) -> SelfT: ...
    @overload  # sparray[-Bool], /, other: sparse +Bool
    def __mul__[SelfT: _SpArrayOut[Any]](self: SelfT, /, other: _spbase[np.bool | _ScalarT_co]) -> SelfT: ...
    @overload  # sparray[-Bool], /, other: array-like +Bool
    def __mul__[ST: _Scalar, ShapeT: tuple[Any, ...]](
        self: sparray[ST, ShapeT], /, other: _To2DLike[bool, np.bool]
    ) -> coo_array[ST, ShapeT]: ...
    @overload  # sparray[-Int], /, other: sparse +Int
    def __mul__[ST: _ToInt](self: sparray[ST], /, other: _spbase[_ToInt8 | ST]) -> _SpArrayOut[ST]: ...
    @overload  # sparray[-Int], /, other: array-like +Int
    def __mul__[ST: npc.number, ShapeT: tuple[Any, ...]](
        self: sparray[ST, ShapeT], /, other: _To2DLike[bool, _ToInt8]
    ) -> coo_array[ST, ShapeT]: ...
    @overload  # sparray[-Float], /, other: sparse +Float
    def __mul__[ST: npc.floating](self: sparray[ST], /, other: _spbase[_ToFloat32 | ST]) -> _SpArrayOut[ST]: ...
    @overload  # sparray[-Float], /, other: array-like +Float
    def __mul__[ST: npc.inexact, ShapeT: tuple[Any, ...]](
        self: sparray[ST, ShapeT], /, other: _To2DLike[int, _ToFloat32]
    ) -> coo_array[ST, ShapeT]: ...
    @overload  # sparray[-Complex], /, other: sparse +Complex
    def __mul__[ST: npc.complexfloating](self: sparray[ST], /, other: _spbase[_ToComplex64 | ST]) -> _SpArrayOut[ST]: ...
    @overload  # sparray[-Complex], /, other: array-like +Complex
    def __mul__[ST: npc.complexfloating, ShapeT: tuple[Any, ...]](
        self: sparray[ST, ShapeT], /, other: _To2DLike[int, _ToComplex64]
    ) -> coo_array[ST, ShapeT]: ...
    @overload  # {bsr,csc,csr_dia}_matrix, other: {bsr,csc,csr_dia}_matrix
    def __mul__[SpMatrixT: bsr_matrix | csc_matrix | csr_matrix | dia_matrix](
        self: SpMatrixT, other: SpMatrixT, /
    ) -> SpMatrixT: ...
    @overload  # {coo,dok,lil}_matrix, other: {coo,dok,lil}_matrix  TODO
    def __mul__[SpMatrixT: (coo_matrix, dok_matrix, lil_matrix)](
        self: SpMatrixT, other: SpMatrixT, /
    ) -> csr_matrix[_ScalarT_co]: ...
    @overload  # spmatrix[-Bool], /, other: sparse +Bool
    def __mul__[ST: _Scalar](self: spmatrix[ST], /, other: _spbase[np.bool]) -> _SpMatrixOut[ST]: ...
    @overload  # spmatrix[-Bool], /, other: array-like +Bool
    def __mul__[ST: _Scalar](self: spmatrix[ST], /, other: _To2D[bool, np.bool]) -> onp.Array2D[ST]: ...
    @overload  # spmatrix[-Int], /, other: sparse +Int
    def __mul__[ST: _ToInt](self: spmatrix[ST], /, other: _spbase[_ToInt8]) -> _SpMatrixOut[ST]: ...
    @overload  # spmatrix[-Int], /, other: array-like +Int
    def __mul__[ST: npc.number](self: spmatrix[ST], /, other: _To2D[bool, _ToInt8]) -> onp.Array2D[ST]: ...
    @overload  # spmatrix[-Float], /, other: sparse +Float
    def __mul__[ST: npc.floating](self: spmatrix[ST], /, other: _spbase[_ToFloat32 | ST]) -> _SpMatrixOut[ST]: ...
    @overload  # spmatrix[-Float], /, other: array-like +Float
    def __mul__[ST: npc.inexact](self: spmatrix[ST], /, other: _To2D[int, _ToFloat32]) -> onp.Array2D[ST]: ...
    @overload  # spmatrix[-Complex], /, other: sparse +Complex
    def __mul__[ST: npc.complexfloating](self: spmatrix[ST], /, other: _spbase[_ToComplex64 | ST]) -> _SpMatrixOut[ST]: ...
    @overload  # spmatrix[-Complex], /, other: array-like +Complex
    def __mul__[ST: npc.complexfloating](self: spmatrix[ST], /, other: _To2D[float, _ToComplex64]) -> onp.Array2D[ST]: ...
    @overload  # spmatrix[+Bool], /, other: scalar- or matrix-like ~Int
    def __mul__(self: spmatrix[np.bool], /, other: _SparseLike[op.JustInt, npc.integer]) -> spmatrix[npc.integer]: ...
    @overload  # spmatrix[+Bool], /, other: array-like ~Int
    def __mul__(self: spmatrix[np.bool], /, other: _To2D[op.JustInt, npc.integer]) -> onp.Array2D[npc.integer]: ...
    @overload  # spmatrix[+Int], /, other: scalar- or matrix-like ~Float
    def __mul__(self: spmatrix[_ToInt], /, other: _SparseLike[op.JustFloat, npc.floating]) -> spmatrix[npc.floating]: ...
    @overload  # spmatrix[+Int], /, other: array-like ~Float
    def __mul__(self: spmatrix[_ToInt], /, other: _To2D[op.JustFloat, npc.floating]) -> onp.Array2D[npc.floating]: ...
    @overload  # spmatrix[+Float], /, other: scalar- or matrix-like ~Complex
    def __mul__(
        self: spmatrix[_ToFloat], /, other: _SparseLike[op.JustComplex, npc.complexfloating]
    ) -> spmatrix[npc.complexfloating]: ...
    @overload  # spmatrix[+Float], /, other: array-like ~Complex
    def __mul__(
        self: spmatrix[_ToFloat], /, other: _To2D[op.JustComplex, npc.complexfloating]
    ) -> onp.Array2D[npc.complexfloating]: ...
    @overload  # Self[+Bool], /, other: -Int
    def __mul__[ST: npc.number, ShapeT: tuple[Any, ...]](self: _spbase[np.bool], /, other: ST) -> _spbase[ST, ShapeT]: ...
    @overload  # Self[+Int], /, other: -Float
    def __mul__[ST: npc.inexact, ShapeT: tuple[Any, ...]](self: _spbase[_ToInt], /, other: ST) -> _spbase[ST, ShapeT]: ...
    @overload  # Self[+Float], /, other: -Complex
    def __mul__[ST: npc.complexfloating, ShapeT: tuple[Any, ...]](
        self: _spbase[_ToFloat, ShapeT], /, other: ST
    ) -> _spbase[ST, ShapeT]: ...
    @overload  # catch-all
    def __mul__(self, /, other: _To2DLike[complex, _Scalar] | _spbase) -> _spbase[Any] | onp.ArrayND[Any]: ...

    # NOTE: unlike `__mul__`, this is always element-wise, so dense operands result in sparse output
    @overload  # Self[-Bool], /, other: scalar-like +Bool
    def multiply(self, /, other: bool | np.bool) -> Self: ...
    @overload  # Self[-Int], /, other: scalar-like +Int
    def multiply[SelfT: _spbase[npc.number]](self: SelfT, /, other: onp.ToInt) -> SelfT: ...
    @overload  # Self[-Float], /, other: scalar-like +Float
    def multiply[SelfT: _spbase[npc.inexact]](self: SelfT, /, other: onp.ToFloat) -> SelfT: ...
    @overload  # Self[-Complex], /, other: scalar-like +Complex
    def multiply[SelfT: _spbase[npc.complexfloating]](self: SelfT, /, other: onp.ToComplex) -> SelfT: ...
    @overload  # sparray[-Bool], /, other: sparse +Bool
    def multiply[SelfT: _SpArrayOut[Any]](self: SelfT, /, other: _spbase[np.bool | _ScalarT_co]) -> SelfT: ...
    @overload  # sparray[-Bool], /, other: array-like +Bool
    def multiply[ST: _Scalar, ShapeT: tuple[Any, ...]](
        self: sparray[ST, ShapeT], /, other: _To2DLike[bool, np.bool]
    ) -> coo_array[ST, ShapeT]: ...
    @overload  # sparray[-Int], /, other: sparse +Int
    def multiply[ST: _ToInt](self: sparray[ST], /, other: _spbase[_ToInt8 | ST]) -> _SpArrayOut[ST]: ...
    @overload  # sparray[-Int], /, other: array-like +Int
    def multiply[ST: npc.number, ShapeT: tuple[Any, ...]](
        self: sparray[ST, ShapeT], /, other: _To2DLike[bool, _ToInt8]
    ) -> coo_array[ST, ShapeT]: ...
    @overload  # sparray[-Float], /, other: sparse +Float
    def multiply[ST: npc.floating](self: sparray[ST], /, other: _spbase[_ToFloat32 | ST]) -> _SpArrayOut[ST]: ...
    @overload  # sparray[-Float], /, other: array-like +Float
    def multiply[ST: npc.inexact, ShapeT: tuple[Any, ...]](
        self: sparray[ST, ShapeT], /, other: _To2DLike[int, _ToFloat32]
    ) -> coo_array[ST, ShapeT]: ...
    @overload  # sparray[-Complex], /, other: sparse +Complex
    def multiply[ST: npc.complexfloating](self: sparray[ST], /, other: _spbase[_ToComplex64 | ST]) -> _SpArrayOut[ST]: ...
    @overload  # sparray[-Complex], /, other: array-like +Complex
    def multiply[ST: npc.complexfloating, ShapeT: tuple[Any, ...]](
        self: sparray[ST, ShapeT], /, other: _To2DLike[int, _ToComplex64]
    ) -> coo_array[ST, ShapeT]: ...
    @overload  # {bsr,csc,csr_dia}_matrix, other: {bsr,csc,csr_dia}_matrix
    def multiply[SpT: bsr_matrix | csc_matrix | csr_matrix | dia_matrix](self: SpT, /, other: SpT) -> SpT: ...
    @overload  # {coo,dok,lil}_matrix, other: {coo,dok,lil}_matrix  TODO
    def multiply[SpT: coo_matrix | dok_matrix | lil_matrix](self: SpT, /, other: SpT) -> csr_matrix[_ScalarT_co]: ...
    @overload  # spmatrix[+Bool], /, other: scalar- or matrix-like ~Int
    def multiply(self: spmatrix[np.bool], /, other: _SparseLike[op.JustInt, _IntT]) -> _SpMatrix[_IntT]: ...
    @overload  # spmatrix[+Bool], /, other: array-like ~Int
    def multiply(self: spmatrix[np.bool], /, other: _To2DLike[op.JustInt, _IntT]) -> coo_matrix[_IntT]: ...
    @overload  # spmatrix[+Int16], /, other: scalar- or matrix-like ~Float
    def multiply(self: spmatrix[_ToInt16], /, other: _SparseLike[op.JustFloat, _FloatT]) -> _SpMatrix[_FloatT]: ...
    @overload  # spmatrix[+Int16], /, other: array-like ~Float
    def multiply(self: spmatrix[_ToInt16], /, other: _To2DLike[op.JustFloat, _FloatT]) -> coo_matrix[_FloatT]: ...
    @overload  # spmatrix[-Int32], /, other: scalar- or matrix-like ~Float
    def multiply(
        self: spmatrix[npc.integer32 | npc.integer64],
        /,
        other: _SparseLike[op.JustFloat | np.float32 | _spbase[np.float32], _Float64T],
    ) -> _SpMatrix[_Float64T]: ...
    @overload  # spmatrix[-Int32], /, other: array-like ~Float
    def multiply(
        self: spmatrix[npc.integer32 | npc.integer64],
        /,
        other: _To2DLike[op.JustFloat | np.float32, _Float64T] | onp.CanArrayND[np.float32],
    ) -> coo_matrix[_Float64T]: ...
    @overload  # spmatrix[Float32], /, other: scalar- or matrix-like ~Complex
    def multiply(self: spmatrix[np.float32], /, other: _SparseLike[op.JustComplex, _Complex64T]) -> _SpMatrix[_Complex64T]: ...
    @overload  # spmatrix[+Int16], /, other: scalar- or matrix-like ~Complex
    def multiply(self: spmatrix[_ToInt16], /, other: _SparseLike[op.JustComplex, _ComplexT]) -> _SpMatrix[_ComplexT]: ...
    @overload  # spmatrix[Float32 | +Int16], /, other: array-like ~Complex
    def multiply(
        self: spmatrix[np.float32 | _ToInt16], /, other: _To2DLike[op.JustComplex, _ComplexT]
    ) -> coo_matrix[_ComplexT]: ...
    @overload  # spmatrix[Float64 | -Int32], /, other: scalar- or matrix-like ~Complex
    def multiply(
        self: spmatrix[np.float64 | npc.integer32 | npc.integer64],
        /,
        other: _SparseLike[op.JustComplex | np.complex64 | _spbase[np.complex64], _Complex128T],
    ) -> _SpMatrix[_Complex128T]: ...
    @overload  # spmatrix[Float64 | -Int32], /, other: array-like ~Complex
    def multiply(
        self: spmatrix[np.float64 | npc.integer32 | npc.integer64],
        /,
        other: _To2DLike[op.JustComplex | np.complex64, _Complex128T] | onp.CanArrayND[np.complex64],
    ) -> coo_matrix[_Complex128T]: ...
    @overload  # spmatrix[LongDouble], /, other: ~Complex
    def multiply(
        self: spmatrix[npc.floating80],
        /,
        other: _SparseLike[op.JustComplex, npc.complexfloating] | _To2DLike[op.JustComplex, npc.complexfloating],
    ) -> _SpMatrix[np.clongdouble]: ...
    @overload  # spmatrix[-Bool], /, other: sparse +Bool
    def multiply[ST: _Scalar](self: spmatrix[ST], /, other: _spbase[np.bool]) -> _SpMatrixOut[ST]: ...
    @overload  # spmatrix[-Bool], /, other: array-like +Bool
    def multiply[ST: _Scalar](self: spmatrix[ST], /, other: _To2DLike[bool, np.bool]) -> coo_matrix[ST]: ...
    @overload  # spmatrix[-Int], /, other: sparse +Int
    def multiply[ST: _ToInt](self: spmatrix[ST], /, other: _spbase[_ToInt8]) -> _SpMatrixOut[ST]: ...
    @overload  # spmatrix[-Int], /, other: array-like +Int
    def multiply[ST: _ToInt](self: spmatrix[ST], /, other: _To2DLike[bool, _ToInt8]) -> coo_matrix[ST]: ...
    @overload  # spmatrix[-Float], /, other: sparse +Float
    def multiply[ST: npc.floating](self: spmatrix[ST], /, other: _spbase[_ToFloat32 | ST]) -> _SpMatrixOut[ST]: ...
    @overload  # spmatrix[-Float], /, other: array-like +Float
    def multiply[ST: npc.floating](self: spmatrix[ST], /, other: _To2DLike[int, _ToFloat32]) -> coo_matrix[ST]: ...
    @overload  # spmatrix[-Complex], /, other: sparse +Complex
    def multiply[ST: npc.complexfloating](self: spmatrix[ST], /, other: _spbase[_ToComplex64 | ST]) -> _SpMatrixOut[ST]: ...
    @overload  # spmatrix[-Complex], /, other: array-like +Complex
    def multiply[ST: npc.complexfloating](self: spmatrix[ST], /, other: _To2DLike[float, _ToComplex64]) -> coo_matrix[ST]: ...
    @overload  # Self[+Bool], /, other: -Int
    def multiply[ST: npc.number, ShapeT: tuple[Any, ...]](
        self: _spbase[np.bool, ShapeT], /, other: ST
    ) -> _spbase[ST, ShapeT]: ...
    @overload  # Self[+Int], /, other: -Float
    def multiply[ST: npc.inexact, ShapeT: tuple[Any, ...]](
        self: _spbase[_ToInt, ShapeT], /, other: ST
    ) -> _spbase[ST, ShapeT]: ...
    @overload  # Self[+Float], /, other: -Complex
    def multiply[ST: npc.complexfloating, ShapeT: tuple[Any, ...]](
        self: _spbase[_ToFloat, ShapeT], /, other: ST
    ) -> _spbase[ST, ShapeT]: ...
    @overload  # catch-all
    def multiply(self, /, other: _To2DLike[complex, _Scalar] | _spbase) -> _spbase[Any]: ...

    # NOTE: `__rmul__ = __mul__` won't work here due to mypy limitations
    # NOTE: keep in sync with `__mul__`
    @overload  # Self[-Bool], /, other: scalar-like +Bool
    def __rmul__(self, /, other: bool | np.bool) -> Self: ...
    @overload  # Self[-Int], /, other: scalar-like +Int
    def __rmul__[SelfT: _spbase[npc.number]](self: SelfT, /, other: onp.ToInt) -> SelfT: ...
    @overload  # Self[-Float], /, other: scalar-like +Float
    def __rmul__[SelfT: _spbase[npc.inexact]](self: SelfT, /, other: onp.ToFloat) -> SelfT: ...
    @overload  # Self[-Complex], /, other: scalar-like +Complex
    def __rmul__[SelfT: _spbase[npc.complexfloating]](self: SelfT, /, other: onp.ToComplex) -> SelfT: ...
    @overload  # sparray[-Bool], /, other: sparse +Bool
    def __rmul__[SelfT: _SpArrayOut[Any]](self: SelfT, /, other: _spbase[np.bool | _ScalarT_co]) -> SelfT: ...
    @overload  # sparray[-Bool], /, other: array-like +Bool
    def __rmul__[ST: _Scalar, ShapeT: tuple[Any, ...]](
        self: sparray[ST, ShapeT], /, other: _To2DLike[bool, np.bool]
    ) -> coo_array[ST, ShapeT]: ...
    @overload  # sparray[-Int], /, other: sparse +Int
    def __rmul__[ST: _ToInt](self: sparray[ST], /, other: _spbase[_ToInt8 | ST]) -> _SpArrayOut[ST]: ...
    @overload  # sparray[-Int], /, other: array-like +Int
    def __rmul__[ST: npc.number, ShapeT: tuple[Any, ...]](
        self: sparray[ST, ShapeT], /, other: _To2DLike[bool, _ToInt8]
    ) -> coo_array[ST, ShapeT]: ...
    @overload  # sparray[-Float], /, other: sparse +Float
    def __rmul__[ST: npc.floating](self: sparray[ST], /, other: _spbase[_ToFloat32 | ST]) -> _SpArrayOut[ST]: ...
    @overload  # sparray[-Float], /, other: array-like +Float
    def __rmul__[ST: npc.inexact, ShapeT: tuple[Any, ...]](
        self: sparray[ST, ShapeT], /, other: _To2DLike[int, _ToFloat32]
    ) -> coo_array[ST, ShapeT]: ...
    @overload  # sparray[-Complex], /, other: sparse +Complex
    def __rmul__[ST: npc.complexfloating](self: sparray[ST], /, other: _spbase[_ToComplex64 | ST]) -> _SpArrayOut[ST]: ...
    @overload  # sparray[-Complex], /, other: array-like +Complex
    def __rmul__[ST: npc.complexfloating, ShapeT: tuple[Any, ...]](
        self: sparray[ST, ShapeT], /, other: _To2DLike[int, _ToComplex64]
    ) -> coo_array[ST, ShapeT]: ...
    @overload  # {bsr,csc,csr_dia}_matrix, other: {bsr,csc,csr_dia}_matrix
    def __rmul__[SpMatrixT: bsr_matrix | csc_matrix | csr_matrix | dia_matrix](
        self: SpMatrixT, other: SpMatrixT, /
    ) -> SpMatrixT: ...
    @overload  # {coo,dok,lil}_matrix, other: {coo,dok,lil}_matrix  TODO
    def __rmul__[SpMatrixT: (coo_matrix, dok_matrix, lil_matrix)](
        self: SpMatrixT, other: SpMatrixT, /
    ) -> csr_matrix[_ScalarT_co]: ...
    @overload  # spmatrix[-Bool], /, other: sparse +Bool
    def __rmul__[ST: _Scalar](self: spmatrix[ST], /, other: _spbase[np.bool]) -> _SpMatrixOut[ST]: ...
    @overload  # spmatrix[-Bool], /, other: array-like +Bool
    def __rmul__[ST: _Scalar](self: spmatrix[ST], /, other: _To2D[bool, np.bool]) -> onp.Array2D[ST]: ...
    @overload  # spmatrix[-Int], /, other: sparse +Int
    def __rmul__[ST: _ToInt](self: spmatrix[ST], /, other: _spbase[_ToInt8]) -> _SpMatrixOut[ST]: ...
    @overload  # spmatrix[-Int], /, other: array-like +Int
    def __rmul__[ST: npc.number](self: spmatrix[ST], /, other: _To2D[bool, _ToInt8]) -> onp.Array2D[ST]: ...
    @overload  # spmatrix[-Float], /, other: sparse +Float
    def __rmul__[ST: npc.floating](self: spmatrix[ST], /, other: _spbase[_ToFloat32 | ST]) -> _SpMatrixOut[ST]: ...
    @overload  # spmatrix[-Float], /, other: array-like +Float
    def __rmul__[ST: npc.inexact](self: spmatrix[ST], /, other: _To2D[int, _ToFloat32]) -> onp.Array2D[ST]: ...
    @overload  # spmatrix[-Complex], /, other: sparse +Complex
    def __rmul__[ST: npc.complexfloating](self: spmatrix[ST], /, other: _spbase[_ToComplex64 | ST]) -> _SpMatrixOut[ST]: ...
    @overload  # spmatrix[-Complex], /, other: array-like +Complex
    def __rmul__[ST: npc.complexfloating](self: spmatrix[ST], /, other: _To2D[float, _ToComplex64]) -> onp.Array2D[ST]: ...
    @overload  # spmatrix[+Bool], /, other: scalar- or matrix-like ~Int
    def __rmul__(self: spmatrix[np.bool], /, other: _SparseLike[op.JustInt, npc.integer]) -> spmatrix[npc.integer]: ...
    @overload  # spmatrix[+Bool], /, other: array-like ~Int
    def __rmul__(self: spmatrix[np.bool], /, other: _To2D[op.JustInt, npc.integer]) -> onp.Array2D[npc.integer]: ...
    @overload  # spmatrix[+Int], /, other: scalar- or matrix-like ~Float
    def __rmul__(self: spmatrix[_ToInt], /, other: _SparseLike[op.JustFloat, npc.floating]) -> spmatrix[npc.floating]: ...
    @overload  # spmatrix[+Int], /, other: array-like ~Float
    def __rmul__(self: spmatrix[_ToInt], /, other: _To2D[op.JustFloat, npc.floating]) -> onp.Array2D[npc.floating]: ...
    @overload  # spmatrix[+Float], /, other: scalar- or matrix-like ~Complex
    def __rmul__(
        self: spmatrix[_ToFloat], /, other: _SparseLike[op.JustComplex, npc.complexfloating]
    ) -> spmatrix[npc.complexfloating]: ...
    @overload  # spmatrix[+Float], /, other: array-like ~Complex
    def __rmul__(
        self: spmatrix[_ToFloat], /, other: _To2D[op.JustComplex, npc.complexfloating]
    ) -> onp.Array2D[npc.complexfloating]: ...
    @overload  # Self[+Bool], /, other: -Int
    def __rmul__[ST: npc.number, ShapeT: tuple[Any, ...]](self: _spbase[np.bool], /, other: ST) -> _spbase[ST, ShapeT]: ...
    @overload  # Self[+Int], /, other: -Float
    def __rmul__[ST: npc.inexact, ShapeT: tuple[Any, ...]](self: _spbase[_ToInt], /, other: ST) -> _spbase[ST, ShapeT]: ...
    @overload  # Self[+Float], /, other: -Complex
    def __rmul__[ST: npc.complexfloating, ShapeT: tuple[Any, ...]](
        self: _spbase[_ToFloat, ShapeT], /, other: ST
    ) -> _spbase[ST, ShapeT]: ...
    @overload  # catch-all
    def __rmul__(self, /, other: _To2DLike[complex, _Scalar] | _spbase) -> _spbase[Any] | onp.ArrayND[Any]: ...

    #
    @overload  # sparray[-Bool], other: sparse +Bool
    def __matmul__[SpT: _SpArrayOut[Any]](self: SpT, other: _spbase[np.bool | _ScalarT_co], /) -> SpT: ...
    @overload  # sparray[-Bool], other: array-like +Bool
    def __matmul__[ST: _Scalar, ShapeT: tuple[Any, ...]](
        self: sparray[ST, ShapeT], other: _To2DLike[bool, np.bool], /
    ) -> onp.ArrayND[ST, ShapeT]: ...
    @overload  # sparray[-Int], other: sparse +Int
    def __matmul__[ST: _ToInt](self: sparray[ST], other: _spbase[_ToInt8 | ST], /) -> _SpArrayOut[ST]: ...
    @overload  # sparray[-Int], other: array-like +Int
    def __matmul__[ST: npc.number, ShapeT: tuple[Any, ...]](
        self: sparray[ST, ShapeT], other: _To2DLike[bool, _ToInt8], /
    ) -> onp.ArrayND[ST, ShapeT]: ...
    @overload  # sparray[-Float], other: sparse +Float
    def __matmul__[ST: npc.floating](self: sparray[ST], other: _spbase[_ToFloat32 | ST], /) -> _SpArrayOut[ST]: ...
    @overload  # sparray[-Float], other: array-like +Float
    def __matmul__[ST: npc.inexact, ShapeT: tuple[Any, ...]](
        self: sparray[ST, ShapeT], other: _To2DLike[int, _ToFloat32], /
    ) -> onp.ArrayND[ST, ShapeT]: ...
    @overload  # sparray[-Complex], other: sparse +Complex
    def __matmul__[ST: npc.complexfloating](self: sparray[ST], other: _spbase[_ToComplex64 | ST], /) -> _SpArrayOut[ST]: ...
    @overload  # sparray[-Complex], other: array-like +Complex
    def __matmul__[ST: npc.complexfloating, ShapeT: tuple[Any, ...]](
        self: sparray[ST, ShapeT], other: _To2DLike[int, _ToComplex64], /
    ) -> onp.ArrayND[ST, ShapeT]: ...
    @overload  # {bsr,csc,csr_dia}_matrix, other: {bsr,csc,csr_dia}_matrix
    def __matmul__[SpMatrixT: bsr_matrix | csc_matrix | csr_matrix | dia_matrix](
        self: SpMatrixT, other: SpMatrixT, /
    ) -> SpMatrixT: ...
    @overload  # {coo,dok,lil}_matrix, other: {coo,dok,lil}_matrix  TODO
    def __matmul__[SpMatrixT: (coo_matrix, dok_matrix, lil_matrix)](
        self: SpMatrixT, other: SpMatrixT, /
    ) -> csr_matrix[_ScalarT_co]: ...
    @overload  # spmatrix[-Bool], other: sparse +Bool
    def __matmul__[ST: _Scalar](self: spmatrix[ST], other: _spbase[np.bool], /) -> _SpMatrixOut[ST]: ...
    @overload  # spmatrix[-Bool], other: array-like +Bool
    def __matmul__[ST: _Scalar](self: spmatrix[ST], other: _To2D[bool, np.bool], /) -> onp.Array2D[ST]: ...
    @overload  # spmatrix[-Int], other: sparse +Int
    def __matmul__[ST: _ToInt](self: spmatrix[ST], other: _spbase[_ToInt8], /) -> _SpMatrixOut[ST]: ...
    @overload  # spmatrix[-Int], other: array-like +Int
    def __matmul__[ST: npc.number](self: spmatrix[ST], other: _To2D[bool, _ToInt8], /) -> onp.Array2D[ST]: ...
    @overload  # spmatrix[-Float], other: sparse +Float
    def __matmul__[ST: npc.floating](self: spmatrix[ST], other: _spbase[_ToFloat32 | ST], /) -> _SpMatrixOut[ST]: ...
    @overload  # spmatrix[-Float], other: array-like +Float
    def __matmul__[ST: npc.inexact](self: spmatrix[ST], other: _To2D[int, _ToFloat32], /) -> onp.Array2D[ST]: ...
    @overload  # spmatrix[-Complex], other: sparse +Complex
    def __matmul__[ST: npc.complexfloating](self: spmatrix[ST], other: _spbase[_ToComplex64 | ST], /) -> _SpMatrixOut[ST]: ...
    @overload  # spmatrix[-Complex], other: array-like +Complex
    def __matmul__[ST: npc.complexfloating](self: spmatrix[ST], other: _To2D[float, _ToComplex64], /) -> onp.Array2D[ST]: ...
    @overload  # spmatrix[+Bool], other: scalar- or matrix-like ~Int
    def __matmul__(self: spmatrix[np.bool], other: _spbase[npc.integer], /) -> _SpMatrixOut[npc.integer]: ...
    @overload  # spmatrix[+Bool], other: array-like ~Int
    def __matmul__(self: spmatrix[np.bool], other: _To2D[op.JustInt, npc.integer], /) -> onp.Array2D[npc.integer]: ...
    @overload  # spmatrix[+Int], other: scalar- or matrix-like ~Float
    def __matmul__(self: spmatrix[_ToInt], other: _spbase[npc.floating], /) -> _SpMatrixOut[npc.floating]: ...
    @overload  # spmatrix[+Int], other: array-like ~Float
    def __matmul__(self: spmatrix[_ToInt], other: _To2D[op.JustFloat, npc.floating], /) -> onp.Array2D[npc.floating]: ...
    @overload  # spmatrix[+Float], other: scalar- or matrix-like ~Complex
    def __matmul__(self: spmatrix[_ToFloat], other: _spbase[npc.complexfloating], /) -> _SpMatrixOut[npc.complexfloating]: ...
    @overload  # spmatrix[+Float], other: array-like ~Complex
    def __matmul__(
        self: spmatrix[_ToFloat], other: _To2D[op.JustComplex, npc.complexfloating], /
    ) -> onp.Array2D[npc.complexfloating]: ...
    @overload  # catch-all
    def __matmul__(self, other: _To2DLike[complex, _Scalar] | _spbase, /) -> _spbase[Any] | onp.ArrayND[Any]: ...

    #
    @overload
    def __truediv__[SelfT: _spbase[np.float64]](self: SelfT, rhs: onp.ToFloat64, /) -> SelfT: ...
    @overload
    def __truediv__[SelfT: _spbase[np.complex128]](self: SelfT, rhs: onp.ToComplex128, /) -> SelfT: ...
    @overload
    def __truediv__[OutT](self: _CanAsAny[OutT], rhs: onp.ToComplex, /) -> OutT: ...
    @overload
    def __truediv__[ShapeT: tuple[Any, ...]](
        self: sparray[_ToFloat, ShapeT], rhs: _spbase[_ToFloat, ShapeT], /
    ) -> onp.ArrayND[np.float64, ShapeT]: ...
    @overload
    def __truediv__(self: spmatrix[_ToFloat], rhs: spmatrix[_ToFloat], /) -> onp.Matrix[np.float64]: ...
    @overload
    def __truediv__(self: sparray, rhs: onp.ArrayND[_Scalar], /) -> coo_array[Any]: ...
    @overload
    def __truediv__(self: spmatrix, rhs: onp.ArrayND[_Scalar], /) -> coo_matrix[Any]: ...
    @overload
    def __truediv__(self: spmatrix, rhs: _spbase[Any, _2D], /) -> onp.Matrix[Any]: ...
    @overload
    def __truediv__[ShapeT: tuple[Any, ...]](self, rhs: _spbase[Any, ShapeT], /) -> onp.ArrayND[Any, ShapeT]: ...

    #
    @overload  # dok_array -> csr_array
    def __pow__[ST: _Scalar, ShapeT: _1D | _2D](self: dok_array[ST, ShapeT], rhs: SupportsIndex, /) -> csr_array[ST, ShapeT]: ...
    @overload  # lil_array -> csr_array
    def __pow__[ST: _Scalar](self: lil_array[ST], rhs: SupportsIndex, /) -> csr_array[ST, _2D]: ...
    @overload  # {coo,dok,lil}_matrix -> csr_matrix
    def __pow__[ST: _Scalar](self: coo_matrix[ST] | dok_matrix[ST] | lil_matrix[ST], rhs: SupportsIndex, /) -> csr_matrix[ST]: ...
    @overload  # otherwise; Self -> Self
    def __pow__[
        SelfT: bsr_array | bsr_matrix | csc_array | csc_matrix | csr_array | csr_matrix | coo_array | dia_array | dia_matrix
    ](self: SelfT, rhs: SupportsIndex, /) -> SelfT: ...

    #
    __radd__ = __add__
    __rsub__ = __sub__
    __rmatmul__ = __matmul__
    def __rtruediv__(self, other: Never, /) -> Never: ...

    #
    def __iadd__(self, other: Never, /) -> Self: ...
    def __isub__(self, other: Never, /) -> Self: ...
    def __imul__(self, other: Never, /) -> Self: ...
    def __itruediv__(self, other: Never, /) -> Self: ...

    # https://github.com/scipy/scipy/pull/23138
    __nonzero__ = __bool__
    __div__ = __truediv__
    __rdiv__ = __rtruediv__
    __idiv__ = __itruediv__

    #
    @overload  # Self[-Bool], /, other: scalar-like +Bool
    def dot(self, /, other: bool | np.bool) -> Self: ...
    @overload  # Self[-Int], /, other: scalar-like +Int
    def dot[SelfT: _spbase[npc.number]](self: SelfT, /, other: onp.ToInt) -> SelfT: ...
    @overload  # Self[-Float], /, other: scalar-like +Float
    def dot[SelfT: _spbase[npc.inexact]](self: SelfT, /, other: onp.ToFloat) -> SelfT: ...
    @overload  # Self[-Complex], /, other: scalar-like +Complex
    def dot[SelfT: _spbase[npc.complexfloating]](self: SelfT, /, other: onp.ToComplex) -> SelfT: ...
    @overload  # spmatrix[+Bool], /, other: scalar-like ~Int
    def dot(self: spmatrix[np.bool], /, other: op.JustInt) -> spmatrix[npc.integer]: ...
    @overload  # spmatrix[+Int], /, other: scalar-like ~Float
    def dot(self: spmatrix[_ToInt], /, other: op.JustFloat) -> spmatrix[npc.floating]: ...
    @overload  # spmatrix[+Float], /, other: scalar-like ~Complex
    def dot(self: spmatrix[_ToFloat], /, other: op.JustComplex) -> spmatrix[npc.complexfloating]: ...
    @overload  # sparray[-Bool], /, other: sparse +Bool
    def dot[SelfT: _SpArrayOut[Any]](self: SelfT, /, other: _spbase[np.bool | _ScalarT_co]) -> SelfT: ...
    @overload  # sparray[-Bool], /, other: array-like +Bool
    def dot[ST: _Scalar, ShapeT: tuple[Any, ...]](
        self: sparray[ST, ShapeT], /, other: _To2DLike[bool, np.bool]
    ) -> onp.ArrayND[ST, ShapeT]: ...
    @overload  # sparray[-Int], /, other: sparse +Int
    def dot[ST: _ToInt](self: sparray[ST], /, other: _spbase[_ToInt8 | ST]) -> _SpArrayOut[ST]: ...
    @overload  # sparray[-Int], /, other: array-like +Int
    def dot[ST: npc.number, ShapeT: tuple[Any, ...]](
        self: sparray[ST, ShapeT], /, other: _To2DLike[bool, _ToInt8]
    ) -> onp.ArrayND[ST, ShapeT]: ...
    @overload  # sparray[-Float], /, other: sparse +Float
    def dot[ST: npc.floating](self: sparray[ST], /, other: _spbase[_ToFloat32 | ST]) -> _SpArrayOut[ST]: ...
    @overload  # sparray[-Float], /, other: array-like +Float
    def dot[ST: npc.inexact, ShapeT: tuple[Any, ...]](
        self: sparray[ST, ShapeT], /, other: _To2DLike[int, _ToFloat32]
    ) -> onp.ArrayND[ST, ShapeT]: ...
    @overload  # sparray[-Complex], /, other: sparse +Complex
    def dot[ST: npc.complexfloating](self: sparray[ST], /, other: _spbase[_ToComplex64 | ST]) -> _SpArrayOut[ST]: ...
    @overload  # sparray[-Complex], /, other: array-like +Complex
    def dot[ST: npc.complexfloating, ShapeT: tuple[Any, ...]](
        self: sparray[ST, ShapeT], /, other: _To2DLike[int, _ToComplex64]
    ) -> onp.ArrayND[ST, ShapeT]: ...
    @overload  # {bsr,csc,csr_dia}_matrix, other: {bsr,csc,csr_dia}_matrix
    def dot[SpMatrixT: bsr_matrix | csc_matrix | csr_matrix | dia_matrix](self: SpMatrixT, /, other: SpMatrixT) -> SpMatrixT: ...
    @overload  # {coo,dok,lil}_matrix, other: {coo,dok,lil}_matrix  TODO
    def dot[SpMatrixT: (coo_matrix, dok_matrix, lil_matrix)](self: SpMatrixT, /, other: SpMatrixT) -> csr_matrix[_ScalarT_co]: ...
    @overload  # spmatrix[-Bool], /, other: sparse +Bool
    def dot[ST: _Scalar](self: spmatrix[ST], /, other: _spbase[np.bool]) -> _SpMatrixOut[ST]: ...
    @overload  # spmatrix[-Bool], /, other: array-like +Bool
    def dot[ST: _Scalar](self: spmatrix[ST], /, other: _To2D[bool, np.bool]) -> onp.Array2D[ST]: ...
    @overload  # spmatrix[-Int], /, other: sparse +Int
    def dot[ST: _ToInt](self: spmatrix[ST], /, other: _spbase[_ToInt8]) -> _SpMatrixOut[ST]: ...
    @overload  # spmatrix[-Int], /, other: array-like +Int
    def dot[ST: npc.number](self: spmatrix[ST], /, other: _To2D[bool, _ToInt8]) -> onp.Array2D[ST]: ...
    @overload  # spmatrix[-Float], /, other: sparse +Float
    def dot[ST: npc.floating](self: spmatrix[ST], /, other: _spbase[_ToFloat32 | ST]) -> _SpMatrixOut[ST]: ...
    @overload  # spmatrix[-Float], /, other: array-like +Float
    def dot[ST: npc.inexact](self: spmatrix[ST], /, other: _To2D[int, _ToFloat32]) -> onp.Array2D[ST]: ...
    @overload  # spmatrix[-Complex], /, other: sparse +Complex
    def dot[ST: npc.complexfloating](self: spmatrix[ST], /, other: _spbase[_ToComplex64 | ST]) -> _SpMatrixOut[ST]: ...
    @overload  # spmatrix[-Complex], /, other: array-like +Complex
    def dot[ST: npc.complexfloating](self: spmatrix[ST], /, other: _To2D[float, _ToComplex64]) -> onp.Array2D[ST]: ...
    @overload  # spmatrix[+Bool], /, other: scalar- or matrix-like ~Int
    def dot(self: spmatrix[np.bool], /, other: _spbase[npc.integer]) -> _SpMatrixOut[npc.integer]: ...
    @overload  # spmatrix[+Bool], /, other: array-like ~Int
    def dot(self: spmatrix[np.bool], /, other: _To2D[op.JustInt, npc.integer]) -> onp.Array2D[npc.integer]: ...
    @overload  # spmatrix[+Int], /, other: scalar- or matrix-like ~Float
    def dot(self: spmatrix[_ToInt], /, other: _spbase[npc.floating]) -> _SpMatrixOut[npc.floating]: ...
    @overload  # spmatrix[+Int], /, other: array-like ~Float
    def dot(self: spmatrix[_ToInt], /, other: _To2D[op.JustFloat, npc.floating]) -> onp.Array2D[npc.floating]: ...
    @overload  # spmatrix[+Float], /, other: scalar- or matrix-like ~Complex
    def dot(self: spmatrix[_ToFloat], /, other: _spbase[npc.complexfloating]) -> _SpMatrixOut[npc.complexfloating]: ...
    @overload  # spmatrix[+Float], /, other: array-like ~Complex
    def dot(
        self: spmatrix[_ToFloat], /, other: _To2D[op.JustComplex, npc.complexfloating]
    ) -> onp.Array2D[npc.complexfloating]: ...
    @overload  # catch-all
    def dot(self, /, other: _To2DLike[complex, _Scalar] | _spbase) -> _spbase[Any] | onp.ArrayND[Any]: ...

    #
    @overload  # Self[-Int], +Int8
    def maximum[SelfT: _spbase[npc.number]](self: SelfT, /, other: bool | _ToInt8 | _spbase[_ToInt8]) -> SelfT: ...
    @overload  # Self[-Float], +Float32
    def maximum[SelfT: _spbase[npc.inexact]](self: SelfT, /, other: int | _ToFloat32 | _spbase[_ToFloat32]) -> SelfT: ...
    @overload  # Self[-Complex], +Complex64
    def maximum[SelfT: _spbase[npc.complexfloating]](
        self: SelfT, /, other: float | _ToComplex64 | _spbase[_ToComplex64]
    ) -> SelfT: ...
    @overload  # bsr_array, sparse or scalar
    def maximum[ST1: _Scalar, ST2: _Scalar](self: bsr_array[ST1], /, other: _spbase[ST2] | ST2) -> bsr_array[ST1 | ST2]: ...
    @overload  # bsr_matrix, sparse or scalar
    def maximum[ST1: _Scalar, ST2: _Scalar](self: bsr_matrix[ST1], /, other: _spbase[ST2] | ST2) -> bsr_matrix[ST1 | ST2]: ...
    @overload  # csc_array, sparse or scalar
    def maximum[ST1: _Scalar, ST2: _Scalar](self: csc_array[ST1], /, other: _spbase[ST2] | ST2) -> csc_array[ST1 | ST2]: ...
    @overload  # csc_matrix, sparse or scalar
    def maximum[ST1: _Scalar, ST2: _Scalar](self: csc_matrix[ST1], /, other: _spbase[ST2] | ST2) -> csc_matrix[ST1 | ST2]: ...
    @overload  # other sparray, sparse or scalar
    def maximum[ST1: _Scalar, ST2: _Scalar](self: _ToCSRArray[ST1], /, other: _spbase[ST2] | ST2) -> csr_array[ST1 | ST2]: ...
    @overload  # other spmatrix, sparse or scalar
    def maximum[ST1: _Scalar, ST2: _Scalar](self: _ToCSRMatrix[ST2], /, other: _spbase[ST2] | ST2) -> csr_matrix[ST1 | ST2]: ...
    @overload  # sparray, dense
    def maximum[ST1: _Scalar, ST2: _Scalar, ShapeT: tuple[int, *tuple[int, ...]]](
        self: sparray[ST1, ShapeT], /, other: onp.ArrayND[ST2]
    ) -> onp.ArrayND[ST1 | ST2, ShapeT]: ...
    @overload  # spmatrix, dense
    def maximum[ST1: _Scalar, ST2: _Scalar](self: spmatrix[ST1], /, other: onp.ArrayND[ST2]) -> onp.Matrix[ST1 | ST2]: ...
    @overload  # sparray, unknown scalar
    def maximum(self: sparray, /, other: onp.ToComplex) -> _SpArrayOut[Any]: ...
    @overload  # spmatrix, unknown scalar
    def maximum(self: spmatrix, /, other: onp.ToComplex) -> _SpMatrixOut[Any]: ...

    # NOTE: signature identical to `maximum`
    @overload  # Self[-Int], +Int8
    def minimum[SelfT: _spbase[npc.number]](self: SelfT, /, other: bool | _ToInt8 | _spbase[_ToInt8]) -> SelfT: ...
    @overload  # Self[-Float], +Float32
    def minimum[SelfT: _spbase[npc.inexact]](self: SelfT, /, other: int | _ToFloat32 | _spbase[_ToFloat32]) -> SelfT: ...
    @overload  # Self[-Complex], +Complex64
    def minimum[SelfT: _spbase[npc.complexfloating]](
        self: SelfT, /, other: float | _ToComplex64 | _spbase[_ToComplex64]
    ) -> SelfT: ...
    @overload  # bsr_array, sparse or scalar
    def minimum[ST1: _Scalar, ST2: _Scalar](self: bsr_array[ST1], /, other: _spbase[ST2] | ST2) -> bsr_array[ST1 | ST2]: ...
    @overload  # bsr_matrix, sparse or scalar
    def minimum[ST1: _Scalar, ST2: _Scalar](self: bsr_matrix[ST1], /, other: _spbase[ST2] | ST2) -> bsr_matrix[ST1 | ST2]: ...
    @overload  # csc_array, sparse or scalar
    def minimum[ST1: _Scalar, ST2: _Scalar](self: csc_array[ST1], /, other: _spbase[ST2] | ST2) -> csc_array[ST1 | ST2]: ...
    @overload  # csc_matrix, sparse or scalar
    def minimum[ST1: _Scalar, ST2: _Scalar](self: csc_matrix[ST1], /, other: _spbase[ST2] | ST2) -> csc_matrix[ST1 | ST2]: ...
    @overload  # other sparray, sparse or scalar
    def minimum[ST1: _Scalar, ST2: _Scalar](self: _ToCSRArray[ST1], /, other: _spbase[ST2] | ST2) -> csr_array[ST1 | ST2]: ...
    @overload  # other spmatrix, sparse or scalar
    def minimum[ST1: _Scalar, ST2: _Scalar](self: _ToCSRMatrix[ST2], /, other: _spbase[ST2] | ST2) -> csr_matrix[ST1 | ST2]: ...
    @overload  # sparray, dense
    def minimum[ST1: _Scalar, ST2: _Scalar, ShapeT: tuple[int, *tuple[int, ...]]](
        self: sparray[ST1, ShapeT], /, other: onp.ArrayND[ST2]
    ) -> onp.ArrayND[ST1 | ST2, ShapeT]: ...
    @overload  # spmatrix, dense
    def minimum[ST1: _Scalar, ST2: _Scalar](self: spmatrix[ST1], /, other: onp.ArrayND[ST2]) -> onp.Matrix[ST1 | ST2]: ...
    @overload  # sparray, unknown scalar
    def minimum(self: sparray, /, other: onp.ToComplex) -> _SpArrayOut[Any]: ...
    @overload  # spmatrix, unknown scalar
    def minimum(self: spmatrix, /, other: onp.ToComplex) -> _SpMatrixOut[Any]: ...

    # NOTE: the `power` format mappings for don't always match with `__pow__`
    @overload  # {csr,dok}_array -> csr_array
    def power[ST: _Scalar, ShapeT: _1D | _2D](
        self: csr_array[ST, ShapeT] | dok_array[ST, ShapeT], /, n: SupportsIndex, dtype: None = None
    ) -> csr_array[ST, ShapeT]: ...
    @overload  # {csr,dok}_array -> csr_array, dtype=<known>
    def power[ST: _Scalar, ShapeT: _1D | _2D](
        self: csr_array[Any, ShapeT] | dok_array[Any, ShapeT], /, n: SupportsIndex, dtype: onp.ToDType[ST]
    ) -> csr_array[ST, ShapeT]: ...
    @overload  # {csr,dok}_array -> csr_array, dtype=<unknown>
    def power[ST: _Scalar, ShapeT: _1D | _2D](
        self: csr_array[Any, ShapeT] | dok_array[Any, ShapeT], /, n: SupportsIndex, dtype: type[complex] | str
    ) -> csr_array[Any, ShapeT]: ...
    @overload  # lil_array -> csr_array
    def power[ST: _Scalar](self: lil_array[ST], /, n: SupportsIndex, dtype: None = None) -> csr_array[ST, _2D]: ...
    @overload  # lil_array -> csr_array, dtype=<known>
    def power[ST: _Scalar](self: lil_array[Any], /, n: SupportsIndex, dtype: onp.ToDType[ST]) -> csr_array[ST, _2D]: ...
    @overload  # lil_array -> csr_array, dtype=<unknown>
    def power(self: lil_array[Any], /, n: SupportsIndex, dtype: type[complex] | str) -> csr_array[Any, _2D]: ...
    @overload  # {csr,dok,lil}_matrix -> csr_matrix
    def power[ST: _Scalar](
        self: csr_matrix[ST] | dok_matrix[ST] | lil_matrix[ST], /, n: SupportsIndex, dtype: None = None
    ) -> csr_matrix[ST]: ...
    @overload  # {csr,dok,lil}_matrix -> csr_matrix, dtype=<known>
    def power[ST: _Scalar](
        self: csr_matrix | dok_matrix | lil_matrix, /, n: SupportsIndex, dtype: onp.ToDType[ST]
    ) -> csr_matrix[ST]: ...
    @overload  # {csr,dok,lil}_matrix -> csr_matrix, dtype=<unknown>
    def power(self: csr_matrix | dok_matrix | lil_matrix, /, n: SupportsIndex, dtype: type[complex] | str) -> csr_matrix[Any]: ...
    @overload  # otherwise, Self -> Self
    def power[SelfT: bsr_array | bsr_matrix | csc_array | csc_matrix | coo_array | coo_matrix | dia_array | dia_matrix](
        self: SelfT, /, n: SupportsIndex, dtype: None = None
    ) -> SelfT: ...
    @overload  # otherwise; Self.__class__ -> Self.__class__ (erased type arguments), dtype=<unknown>
    def power[SelfKindT: (bsr_array, bsr_matrix, csc_array, csc_matrix, coo_array, coo_matrix, dia_array, dia_matrix)](
        self: SelfKindT, /, n: SupportsIndex, dtype: onp.ToDType[_Scalar] | type[complex] | str
    ) -> SelfKindT: ...

    #
    @overload
    def nonzero(self: _spbase[Any, _2D], /) -> tuple[onp.Array1D[np.int32], onp.Array1D[np.int32]]: ...
    @overload
    def nonzero(self: _spbase[Any, _1D], /) -> tuple[onp.Array1D[np.int32]]: ...
    @overload
    def nonzero(self, /) -> tuple[onp.Array1D[np.int32], ...]: ...

    #
    def count_nonzero(self, /, axis: None = None) -> np.intp: ...
    def conjugate(self, /, copy: bool = True) -> Self: ...
    def conj(self, /, copy: bool = True) -> Self: ...

    # NOTE: CSC and CSR do not return `Self`, but instead return a CSR or CSC array/matrix, respectively.
    # So this property and method are overridden in those classes (my apologies, Miss Liskov).
    @property
    def T[OutT](self: _CanTranspose[OutT], /) -> OutT: ...
    def transpose(self, /, axes: None = None, copy: bool = False) -> Self: ...

    #
    @property
    def mT[SelfT: _spbase[Any, onp.AtLeast2D]](self: SelfT) -> SelfT: ...  # ruff: ignore[custom-type-var-for-self]

    #
    def diagonal(self, /, k: int = 0) -> onp.Array1D[_ScalarT_co]: ...  # only if 2-d

    #
    @overload
    def trace(self: _spbase[Never], /, offset: int = 0) -> Any: ...
    @overload
    def trace(self: _spbase[np.bool | npc.signedinteger], /, offset: int = 0) -> np.int_: ...
    @overload
    def trace(self: _spbase[npc.unsignedinteger], /, offset: int = 0) -> np.uint64: ...
    @overload
    def trace[InexactT: npc.inexact](self: _spbase[InexactT], /, offset: int = 0) -> InexactT: ...
    @overload
    def trace(self, /, offset: int = 0) -> Any: ...

    #
    @overload  # out: array (keyword)
    def sum[ArrayT: onp.ArrayND](
        self, /, axis: SupportsIndex | None = None, dtype: npt.DTypeLike | None = None, *, out: ArrayT
    ) -> ArrayT: ...
    @overload  # axis: None = ..., dtype: <known>  (keyword)
    def sum[ST: _Scalar](self, /, axis: None = None, *, dtype: onp.ToDType[ST], out: None = None) -> ST: ...
    @overload  # Self[?], axis: None
    def sum(self: _spbase[Never], /, axis: None = None, dtype: None = None, out: None = None) -> Any: ...
    @overload  # Self[+Int], axis: None
    def sum(
        self: _spbase[np.bool | npc.signedinteger], /, axis: None = None, dtype: None = None, out: None = None
    ) -> np.int_: ...
    @overload  # Self[+UInt], axis: None
    def sum(self: _spbase[npc.unsignedinteger], /, axis: None = None, dtype: None = None, out: None = None) -> np.uint64: ...
    @overload  # Self[-Float], axis: None
    def sum[InexactT: npc.inexact](
        self: _spbase[InexactT], /, axis: None = None, dtype: None = None, out: None = None
    ) -> InexactT: ...
    @overload  # sparray[?, 2d], axis: index
    def sum(self: _SpArray2D[Never], /, axis: SupportsIndex, dtype: None = None, out: None = None) -> onp.Array1D[Any]: ...
    @overload  # sparray[+Int, 2d], axis: index
    def sum(
        self: _SpArray2D[np.bool | npc.signedinteger], /, axis: SupportsIndex, dtype: None = None, out: None = None
    ) -> onp.Array1D[np.int_]: ...
    @overload  # sparray[+UInt, 2d], axis: index
    def sum(
        self: _SpArray2D[npc.unsignedinteger], /, axis: SupportsIndex, dtype: None = None, out: None = None
    ) -> onp.Array1D[np.uint64]: ...
    @overload  # sparray[-Float, 2d], axis: index
    def sum[InexactT: npc.inexact](
        self: _SpArray2D[InexactT], /, axis: SupportsIndex, dtype: None = None, out: None = None
    ) -> onp.Array1D[InexactT]: ...
    @overload  # sparray[?, 1d], axis: index
    def sum(self: _SpArray1D[Never], /, axis: SupportsIndex | None = None, dtype: None = None, out: None = None) -> Any: ...
    @overload  # sparray[+Int, 1d], axis: index
    def sum(
        self: _SpArray1D[np.bool | npc.signedinteger], /, axis: SupportsIndex | None = None, dtype: None = None, out: None = None
    ) -> np.int_: ...
    @overload  # sparray[+UInt, 1d], axis: index
    def sum(
        self: _SpArray1D[npc.unsignedinteger], /, axis: SupportsIndex | None = None, dtype: None = None, out: None = None
    ) -> np.uint64: ...
    @overload  # sparray[-Float, 1d], axis: index
    def sum[InexactT: npc.inexact](
        self: _SpArray1D[InexactT], /, axis: SupportsIndex | None = None, dtype: None = None, out: None = None
    ) -> InexactT: ...
    @overload  # spmatrix[?], axis: index
    def sum(self: spmatrix[Never], /, axis: SupportsIndex, dtype: None = None, out: None = None) -> onp.Matrix[Any]: ...
    @overload  # spmatrix[+Int], axis: index
    def sum(
        self: spmatrix[np.bool | npc.signedinteger], /, axis: SupportsIndex, dtype: None = None, out: None = None
    ) -> onp.Matrix[np.int_]: ...
    @overload  # spmatrix[+UInt], axis: index
    def sum(
        self: spmatrix[npc.unsignedinteger], /, axis: SupportsIndex, dtype: None = None, out: None = None
    ) -> onp.Matrix[np.uint64]: ...
    @overload  # spmatrix[-Float], axis: index
    def sum[InexactT: npc.inexact](
        self: spmatrix[InexactT], /, axis: SupportsIndex, dtype: None = None, out: None = None
    ) -> onp.Matrix[InexactT]: ...
    @overload  # spmatrix, axis: index, dtype: <unknown>
    def sum(self: spmatrix, /, axis: SupportsIndex, dtype: npt.DTypeLike, out: None = None) -> onp.Matrix[Any]: ...
    @overload  # dtype: <unknown>  (keyword)
    def sum(self, /, axis: SupportsIndex | None = None, *, dtype: npt.DTypeLike, out: None = None) -> Any: ...

    #
    @overload  # out: array (keyword)
    def mean[ArrayT: onp.ArrayND](
        self, /, axis: SupportsIndex | None = None, dtype: npt.DTypeLike | None = None, *, out: ArrayT
    ) -> ArrayT: ...
    @overload  # axis: None = ..., dtype: <known>  (keyword)
    def mean[ST: _Scalar](self, /, axis: None = None, *, dtype: onp.ToDType[ST], out: None = None) -> ST: ...
    @overload  # Self[?], axis: None = ...
    def mean(self: _spbase[Never], /, axis: None = None, dtype: None = None, out: None = None) -> Any: ...
    @overload  # Self[+Int], axis: None = ...
    def mean(self: _spbase[np.bool | npc.integer], /, axis: None = None, dtype: None = None, out: None = None) -> np.float64: ...
    @overload  # Self[-Float], axis: None = ...
    def mean[InexactT: npc.inexact](
        self: _spbase[InexactT], /, axis: None = None, dtype: None = None, out: None = None
    ) -> InexactT: ...
    @overload  # sparray[?, 2d], axis: index
    def mean(self: _SpArray2D[Never], /, axis: SupportsIndex, dtype: None = None, out: None = None) -> onp.Array1D[Any]: ...
    @overload  # sparray[+Int, 2d], axis: index
    def mean(
        self: _SpArray2D[np.bool | npc.integer], /, axis: SupportsIndex, dtype: None = None, out: None = None
    ) -> onp.Array1D[np.float64]: ...
    @overload  # sparray[-Float, 2d], axis: index
    def mean[InexactT: npc.inexact](
        self: _SpArray2D[InexactT], /, axis: SupportsIndex, dtype: None = None, out: None = None
    ) -> onp.Array1D[InexactT]: ...
    @overload  # sparray[?, 1d]
    def mean(self: _SpArray1D[Never], /, axis: SupportsIndex | None = None, dtype: None = None, out: None = None) -> Any: ...
    @overload  # sparray[+Int, 1d]
    def mean(
        self: _SpArray1D[np.bool | npc.integer], /, axis: SupportsIndex | None = None, dtype: None = None, out: None = None
    ) -> np.float64: ...
    @overload  # sparray[-Float, 1d]
    def mean[InexactT: npc.inexact](
        self: _SpArray1D[InexactT], /, axis: SupportsIndex | None = None, dtype: None = None, out: None = None
    ) -> InexactT: ...
    @overload  # spmatrix[?], axis: index
    def mean(self: spmatrix[Never], /, axis: SupportsIndex, dtype: None = None, out: None = None) -> onp.Matrix[Any]: ...
    @overload  # spmatrix[+Int], axis: index
    def mean(
        self: spmatrix[np.bool | npc.integer], /, axis: SupportsIndex, dtype: None = None, out: None = None
    ) -> onp.Matrix[np.float64]: ...
    @overload  # spmatrix[-Float], axis: index
    def mean[InexactT: npc.inexact](
        self: spmatrix[InexactT], /, axis: SupportsIndex, dtype: None = None, out: None = None
    ) -> onp.Matrix[InexactT]: ...
    @overload  # spmatrix, axis: index, dtype: <unknown>
    def mean(self: spmatrix, /, axis: SupportsIndex, dtype: npt.DTypeLike, out: None = None) -> onp.Matrix[Any]: ...
    @overload  # dtype: <unknown>  (keyword)
    def mean(self, /, axis: SupportsIndex | None = None, *, dtype: npt.DTypeLike, out: None = None) -> Any: ...

    #
    def copy(self, /) -> Self: ...

    #
    @overload
    def reshape[Sp1DT: _spbase[_Scalar, _1D]](
        self: Sp1DT, shape: tuple[SupportsIndex], /, *, order: L["C", "F"] = "C", copy: bool = False
    ) -> Sp1DT: ...
    @overload
    def reshape[Sp2DT: _spbase[_Scalar, _2D]](
        self: Sp2DT, shape: tuple[SupportsIndex, SupportsIndex], /, *, order: L["C", "F"] = "C", copy: bool = False
    ) -> Sp2DT: ...

    #
    @overload  # current type
    def astype(self, /, dtype: onp.ToDType[_ScalarT_co], casting: _Casting = "unsafe", copy: bool = True) -> Self: ...
    @overload  # known type -> sparray
    def astype[ST: _Scalar](
        self: bsr_array, /, dtype: onp.ToDType[ST], casting: _Casting = "unsafe", copy: bool = True
    ) -> bsr_array[ST]: ...
    @overload
    def astype[ST: _Scalar, ShapeT: tuple[int, *tuple[int, ...]]](
        self: coo_array[Any, ShapeT], /, dtype: onp.ToDType[ST], casting: _Casting = "unsafe", copy: bool = True
    ) -> coo_array[ST, ShapeT]: ...
    @overload
    def astype[ST: _Scalar](
        self: csc_array, /, dtype: onp.ToDType[ST], casting: _Casting = "unsafe", copy: bool = True
    ) -> csc_array[ST]: ...
    @overload
    def astype[ST: _Scalar, ShapeT: _1D | _2D](
        self: csr_array[Any, ShapeT], /, dtype: onp.ToDType[ST], casting: _Casting = "unsafe", copy: bool = True
    ) -> csr_array[ST, ShapeT]: ...
    @overload
    def astype[ST: _Scalar](
        self: dia_array, /, dtype: onp.ToDType[ST], casting: _Casting = "unsafe", copy: bool = True
    ) -> dia_array[ST]: ...
    @overload
    def astype[ST: _Scalar, ShapeT: _1D | _2D](
        self: dok_array[Any, ShapeT], /, dtype: onp.ToDType[ST], casting: _Casting = "unsafe", copy: bool = True
    ) -> dok_array[ST, ShapeT]: ...
    @overload
    def astype[ST: _Scalar](
        self: lil_array, /, dtype: onp.ToDType[ST], casting: _Casting = "unsafe", copy: bool = True
    ) -> lil_array[ST]: ...
    @overload  # known type -> spmatrix
    def astype[ST: _Scalar](
        self: bsr_matrix, /, dtype: onp.ToDType[ST], casting: _Casting = "unsafe", copy: bool = True
    ) -> bsr_matrix[ST]: ...
    @overload
    def astype[ST: _Scalar](
        self: coo_matrix, /, dtype: onp.ToDType[ST], casting: _Casting = "unsafe", copy: bool = True
    ) -> coo_matrix[ST]: ...
    @overload
    def astype[ST: _Scalar](
        self: csc_matrix, /, dtype: onp.ToDType[ST], casting: _Casting = "unsafe", copy: bool = True
    ) -> csc_matrix[ST]: ...
    @overload
    def astype[ST: _Scalar](
        self: csr_matrix, /, dtype: onp.ToDType[ST], casting: _Casting = "unsafe", copy: bool = True
    ) -> csr_matrix[ST]: ...
    @overload
    def astype[ST: _Scalar](
        self: dia_matrix, /, dtype: onp.ToDType[ST], casting: _Casting = "unsafe", copy: bool = True
    ) -> dia_matrix[ST]: ...
    @overload
    def astype[ST: _Scalar](
        self: dok_matrix, /, dtype: onp.ToDType[ST], casting: _Casting = "unsafe", copy: bool = True
    ) -> dok_matrix[ST]: ...
    @overload
    def astype[ST: _Scalar](
        self: lil_matrix, /, dtype: onp.ToDType[ST], casting: _Casting = "unsafe", copy: bool = True
    ) -> lil_matrix[ST]: ...
    @overload  # catch-all
    def astype(self, /, dtype: npt.DTypeLike, casting: _Casting = "unsafe", copy: bool = True) -> _spbase[Any, _ShapeT_co]: ...

    #
    @overload
    def asformat[ST: _Scalar](self: sparray[ST, _2D], /, format: L["bsr"], copy: bool = False) -> bsr_array[ST]: ...
    @overload
    def asformat[ST: _Scalar](self: spmatrix[ST], /, format: L["bsr"], copy: bool = False) -> bsr_matrix[ST]: ...
    @overload
    def asformat[ST: _Scalar, ShapeT: tuple[Any, ...]](
        self: sparray, /, format: L["coo"], copy: bool = False
    ) -> coo_array[ST, ShapeT]: ...
    @overload
    def asformat[ST: _Scalar](self: spmatrix[ST], /, format: L["coo"], copy: bool = False) -> coo_matrix[ST]: ...
    @overload
    def asformat[ST: _Scalar](self: sparray[ST, _2D], /, format: L["csc"], copy: bool = False) -> csc_array[ST]: ...
    @overload
    def asformat[ST: _Scalar](self: spmatrix[ST], /, format: L["csc"], copy: bool = False) -> csc_matrix[ST]: ...
    @overload
    def asformat[ST: _Scalar, ShapeT: tuple[Any, ...]](
        self: sparray[ST, ShapeT], /, format: L["csr"], copy: bool = False
    ) -> csr_array[ST, ShapeT]: ...
    @overload
    def asformat[ST: _Scalar](self: spmatrix[ST], /, format: L["csr"], copy: bool = False) -> csr_matrix[ST]: ...
    @overload
    def asformat[ST: _Scalar](self: sparray[ST, _2D], /, format: L["dia"], copy: bool = False) -> dia_array[ST]: ...
    @overload
    def asformat[ST: _Scalar](self: spmatrix[ST], /, format: L["dia"], copy: bool = False) -> dia_matrix[ST]: ...
    @overload
    def asformat[ST: _Scalar, ShapeT: tuple[Any, ...]](
        self: sparray[ST, ShapeT], /, format: L["dok"], copy: bool = False
    ) -> dok_array[ST, ShapeT]: ...
    @overload
    def asformat[ST: _Scalar](self: spmatrix[ST], /, format: L["dok"], copy: bool = False) -> dok_matrix[ST]: ...
    @overload
    def asformat[ST: _Scalar](self: sparray[ST, _2D], /, format: L["lil"], copy: bool = False) -> lil_array[ST]: ...
    @overload
    def asformat[ST: _Scalar](self: spmatrix[ST], /, format: L["lil"], copy: bool = False) -> lil_matrix[ST]: ...

    #
    @overload  # self: spmatrix, out: None
    def todense[ST: _Scalar](self: spmatrix[ST], /, order: L["C", "F"] | None = None, out: None = None) -> onp.Matrix[ST]: ...
    @overload  # self: spmatrix, out: array (positional)
    def todense[ST: _Scalar](self: spmatrix[Any], /, order: L["C", "F"] | None, out: onp.ArrayND[ST]) -> onp.Matrix[ST]: ...
    @overload  # self: spmatrix, out: array (keyword)
    def todense[ST: _Scalar](
        self: spmatrix[Any], /, order: L["C", "F"] | None = None, *, out: onp.ArrayND[ST]
    ) -> onp.Matrix[ST]: ...
    @overload  # out: None
    def todense(self, /, order: L["C", "F"] | None = None, out: None = None) -> onp.ArrayND[_ScalarT_co, _ShapeT_co]: ...
    @overload  # out: array (positional)
    def todense[ArrayT: onp.ArrayND](self, /, order: L["C", "F"] | None, out: ArrayT) -> ArrayT: ...
    @overload  # out: array (keyword)
    def todense[ArrayT: onp.ArrayND](self, /, order: L["C", "F"] | None = None, *, out: ArrayT) -> ArrayT: ...

    #
    @overload  # out: None
    def toarray(self, /, order: L["C", "F"] | None = None, out: None = None) -> onp.ArrayND[_ScalarT_co, _ShapeT_co]: ...
    @overload  # out: array (positional)
    def toarray[ArrayT: onp.ArrayND](self, /, order: L["C", "F"] | None, out: ArrayT) -> ArrayT: ...
    @overload  # out: array  (keyword)
    def toarray[ArrayT: onp.ArrayND](self, /, order: L["C", "F"] | None = None, *, out: ArrayT) -> ArrayT: ...

    #
    @overload
    def tobsr[ST: _Scalar](self: sparray[ST, _2D], /, blocksize: _2D | None = None, copy: bool = False) -> bsr_array[ST]: ...
    @overload
    def tobsr[ST: _Scalar](self: spmatrix[ST], /, blocksize: _2D | None = None, copy: bool = False) -> bsr_matrix[ST]: ...

    #
    @overload
    def tocoo[ST: _Scalar, ShapeT: tuple[Any, ...]](
        self: sparray[ST, ShapeT], /, copy: bool = False
    ) -> coo_array[ST, ShapeT]: ...
    @overload
    def tocoo[ST: _Scalar](self: spmatrix[ST], /, copy: bool = False) -> coo_matrix[ST]: ...

    #
    @overload
    def tocsc[ST: _Scalar](self: sparray[ST, _2D], /, copy: bool = False) -> csc_array[ST]: ...
    @overload
    def tocsc[ST: _Scalar](self: spmatrix[ST], /, copy: bool = False) -> csc_matrix[ST]: ...

    #
    @overload
    def tocsr[ST: _Scalar, ShapeT: tuple[Any, ...]](
        self: sparray[ST, ShapeT], /, copy: bool = False
    ) -> csr_array[ST, ShapeT]: ...
    @overload
    def tocsr[ST: _Scalar](self: spmatrix[ST], /, copy: bool = False) -> csr_matrix[ST]: ...

    #
    @overload
    def todia[ST: _Scalar](self: sparray[ST, _2D], /, copy: bool = False) -> dia_array[ST]: ...
    @overload
    def todia[ST: _Scalar](self: spmatrix[ST], /, copy: bool = False) -> dia_matrix[ST]: ...

    #
    @overload
    def todok[ST: _Scalar, ShapeT: tuple[Any, ...]](
        self: sparray[ST, ShapeT], /, copy: bool = False
    ) -> dok_array[ST, ShapeT]: ...
    @overload
    def todok[ST: _Scalar](self: spmatrix[ST], /, copy: bool = False) -> dok_matrix[ST]: ...

    #
    @overload
    def tolil[ST: _Scalar](self: sparray[ST, _2D], /, copy: bool = False) -> lil_array[ST]: ...
    @overload
    def tolil[ST: _Scalar](self: spmatrix[ST], /, copy: bool = False) -> lil_matrix[ST]: ...

    # NOTE: Don't do this; it's type-unsafe.
    def resize(self, /, shape: Never) -> None: ...

    #
    def setdiag(self, /, values: onp.ToComplex | onp.ToComplex1D, k: int = 0) -> None: ...

class sparray(Generic[_ScalarT_co, _ShapeT_co]):
    # NOTE: These two methods do not exist at runtime.
    # See the relevant comment in `_spbase` for more information.
    @type_check_only
    def __assoc_stacked__(self, /) -> _StackedSparseArray[_ScalarT_co]: ...
    @type_check_only
    def __assoc_stacked_as__[ST: _Scalar](self, sctype: ST, /) -> _StackedSparseArray[ST]: ...

    #
    @classmethod
    def __class_getitem__(cls, arg: type | object, /) -> GenericAlias: ...

def isspmatrix(x: object) -> TypeIs[spmatrix]: ...
