from collections.abc import Sequence
from typing import Any, Generic, Literal, Never, Protocol, Self, SupportsIndex, final, overload, override, type_check_only
from typing_extensions import TypeVar

import numpy as np
import optype.numpy as onp
import optype.numpy.compat as npc

from ._base import _spbase, sparray
from ._coo import coo_array, coo_matrix
from ._matrix import spmatrix
from ._sputils import _ScalarLike

__all__: list[str] = []

type _Scalar = npc.number | np.bool

_ScalarT_co = TypeVar("_ScalarT_co", bound=_Scalar, default=Any, covariant=True)
_ShapeT_co = TypeVar("_ShapeT_co", bound=tuple[int, *tuple[int, ...]], default=tuple[Any, ...], covariant=True)
_DataMatrixT_co = TypeVar("_DataMatrixT_co", bound=_data_matrix[Any, Any], covariant=True)

@final
@type_check_only
class _CanAsFloat32(Protocol[_DataMatrixT_co]):
    @property
    def dtype(self, /) -> np.dtype[npc.integer16]: ...
    @type_check_only
    def __assoc_as_float32__(self, /) -> _DataMatrixT_co: ...

@final
@type_check_only
class _CanAsFloat64(Protocol[_DataMatrixT_co]):
    @property
    def dtype(self, /) -> np.dtype[npc.integer32 | npc.integer64]: ...
    @type_check_only
    def __assoc_as_float64__(self, /) -> _DataMatrixT_co: ...

###

class _data_matrix(_spbase[_ScalarT_co, _ShapeT_co], Generic[_ScalarT_co, _ShapeT_co]):
    # NOTE: These two methods do not exist at runtime.
    @type_check_only
    def __assoc_as_float32__(self, /) -> _data_matrix[np.float32, _ShapeT_co]: ...
    @type_check_only
    def __assoc_as_float64__(self, /) -> _data_matrix[np.float64, _ShapeT_co]: ...

    #
    @property
    @override
    def format(self, /) -> Literal["bsr", "coo", "csc", "csr", "dia"]: ...

    #
    @property
    def dtype(self, /) -> np.dtype[_ScalarT_co]: ...
    @dtype.setter
    def dtype(self, newtype: Never, /) -> None: ...

    #
    @overload
    def __init__(
        self, /, arg1: _spbase[_ScalarT_co, _ShapeT_co] | onp.CanArrayND[_ScalarT_co, _ShapeT_co], *, maxprint: int | None = None
    ) -> None: ...
    @overload
    def __init__[ST: _Scalar](
        self: _data_matrix[ST, tuple[int]], /, arg1: Sequence[ST], *, maxprint: int | None = None
    ) -> None: ...
    @overload
    def __init__[ST: _Scalar](
        self: _data_matrix[ST, tuple[int, int]],
        /,
        arg1: Sequence[onp.CanArrayND[ST] | Sequence[ST]],
        *,
        maxprint: int | None = None,
    ) -> None: ...
    @overload
    def __init__(
        self: _data_matrix[np.float64, tuple[int]], /, arg1: tuple[SupportsIndex], *, maxprint: int | None = None
    ) -> None: ...
    @overload
    def __init__(
        self: _data_matrix[np.float64, tuple[int, int]],
        /,
        arg1: tuple[SupportsIndex, SupportsIndex],
        *,
        maxprint: int | None = None,
    ) -> None: ...
    @overload
    def __init__(self, /, arg1: onp.CanArrayND[_ScalarT_co], *, maxprint: int | None = None) -> None: ...

    #
    @override
    def __imul__(self, rhs: _ScalarLike, /) -> Self: ...  # type: ignore[override]
    @override
    def __itruediv__(self, rhs: _ScalarLike, /) -> Self: ...  # type: ignore[override]

    # NOTE: The following methods do not convert the scalar type
    def sign(self, /) -> Self: ...
    def ceil(self, /) -> Self: ...
    def floor(self, /) -> Self: ...
    def rint(self, /) -> Self: ...
    def trunc(self, /) -> Self: ...

    #
    @overload
    def sqrt[OutT: _data_matrix[Any, Any]](self: _CanAsFloat32[OutT], /) -> OutT: ...
    @overload
    def sqrt[OutT: _data_matrix[Any, Any]](self: _CanAsFloat64[OutT], /) -> OutT: ...
    @overload
    def sqrt(self, /) -> Self: ...

    #
    @overload
    def expm1[OutT: _data_matrix[Any, Any]](self: _CanAsFloat32[OutT], /) -> OutT: ...
    @overload
    def expm1[OutT: _data_matrix[Any, Any]](self: _CanAsFloat64[OutT], /) -> OutT: ...
    @overload
    def expm1(self, /) -> Self: ...
    #
    @overload
    def log1p[OutT: _data_matrix[Any, Any]](self: _CanAsFloat32[OutT], /) -> OutT: ...
    @overload
    def log1p[OutT: _data_matrix[Any, Any]](self: _CanAsFloat64[OutT], /) -> OutT: ...
    @overload
    def log1p(self, /) -> Self: ...

    #
    @overload
    def sin[OutT: _data_matrix[Any, Any]](self: _CanAsFloat32[OutT], /) -> OutT: ...
    @overload
    def sin[OutT: _data_matrix[Any, Any]](self: _CanAsFloat64[OutT], /) -> OutT: ...
    @overload
    def sin(self, /) -> Self: ...
    #
    @overload
    def arcsin[OutT: _data_matrix[Any, Any]](self: _CanAsFloat32[OutT], /) -> OutT: ...
    @overload
    def arcsin[OutT: _data_matrix[Any, Any]](self: _CanAsFloat64[OutT], /) -> OutT: ...
    @overload
    def arcsin(self, /) -> Self: ...
    #
    @overload
    def sinh[OutT: _data_matrix[Any, Any]](self: _CanAsFloat32[OutT], /) -> OutT: ...
    @overload
    def sinh[OutT: _data_matrix[Any, Any]](self: _CanAsFloat64[OutT], /) -> OutT: ...
    @overload
    def sinh(self, /) -> Self: ...
    #
    @overload
    def arcsinh[OutT: _data_matrix[Any, Any]](self: _CanAsFloat32[OutT], /) -> OutT: ...
    @overload
    def arcsinh[OutT: _data_matrix[Any, Any]](self: _CanAsFloat64[OutT], /) -> OutT: ...
    @overload
    def arcsinh(self, /) -> Self: ...
    #
    @overload
    def tan[OutT: _data_matrix[Any, Any]](self: _CanAsFloat32[OutT], /) -> OutT: ...
    @overload
    def tan[OutT: _data_matrix[Any, Any]](self: _CanAsFloat64[OutT], /) -> OutT: ...
    @overload
    def tan(self, /) -> Self: ...
    #
    @overload
    def arctan[OutT: _data_matrix[Any, Any]](self: _CanAsFloat32[OutT], /) -> OutT: ...
    @overload
    def arctan[OutT: _data_matrix[Any, Any]](self: _CanAsFloat64[OutT], /) -> OutT: ...
    @overload
    def arctan(self, /) -> Self: ...
    #
    @overload
    def tanh[OutT: _data_matrix[Any, Any]](self: _CanAsFloat32[OutT], /) -> OutT: ...
    @overload
    def tanh[OutT: _data_matrix[Any, Any]](self: _CanAsFloat64[OutT], /) -> OutT: ...
    @overload
    def tanh(self, /) -> Self: ...
    #
    @overload
    def arctanh[OutT: _data_matrix[Any, Any]](self: _CanAsFloat32[OutT], /) -> OutT: ...
    @overload
    def arctanh[OutT: _data_matrix[Any, Any]](self: _CanAsFloat64[OutT], /) -> OutT: ...
    @overload
    def arctanh(self, /) -> Self: ...

    #
    @overload
    def deg2rad[OutT: _data_matrix[Any, Any]](self: _CanAsFloat32[OutT], /) -> OutT: ...
    @overload
    def deg2rad[OutT: _data_matrix[Any, Any]](self: _CanAsFloat64[OutT], /) -> OutT: ...
    @overload
    def deg2rad(self, /) -> Self: ...
    #
    @overload
    def rad2deg[OutT: _data_matrix[Any, Any]](self: _CanAsFloat32[OutT], /) -> OutT: ...
    @overload
    def rad2deg[OutT: _data_matrix[Any, Any]](self: _CanAsFloat64[OutT], /) -> OutT: ...
    @overload
    def rad2deg(self, /) -> Self: ...

class _minmax_mixin(Generic[_ScalarT_co, _ShapeT_co]):
    # NOTE: The following 4 methods have identical signatures
    @overload  # axis: None = ..., out: None = ...
    def max(self, /, axis: None = None, out: None = None, *, explicit: bool = False) -> _ScalarT_co: ...
    @overload  # 1-d, axis: int, out: None = ...
    def max[ST: _Scalar](
        self: _minmax_mixin[ST, tuple[int]], /, axis: onp.ToInt | None = None, out: None = None, *, explicit: bool = False
    ) -> ST: ...
    @overload  # sparray, axis: int, out: None = ...
    def max[ST: _Scalar](  # type: ignore[misc]
        self: sparray[ST],  # zuban: ignore[misc]
        /,
        axis: onp.ToInt,
        out: None = None,
        *,
        explicit: bool = False,
    ) -> coo_array[ST, tuple[int]]: ...
    @overload  # spmatrix, axis: int, out: None = ...
    def max[ST: _Scalar](  # type: ignore[misc]
        self: spmatrix[ST],  # zuban: ignore[misc]
        /,
        axis: onp.ToInt,
        out: None = None,
        *,
        explicit: bool = False,
    ) -> coo_matrix[ST]: ...
    #
    @overload  # axis: None = ..., out: None = ...
    def nanmax(self, /, axis: None = None, out: None = None, *, explicit: bool = False) -> _ScalarT_co: ...
    @overload  # 1-d, axis: int, out: None = ...
    def nanmax[ST: _Scalar](
        self: _minmax_mixin[ST, tuple[int]], /, axis: onp.ToInt | None = None, out: None = None, *, explicit: bool = False
    ) -> ST: ...
    @overload  # sparray, axis: int, out: None = ...
    def nanmax[ST: _Scalar](  # type: ignore[misc]
        self: sparray[ST],  # zuban: ignore[misc]
        /,
        axis: onp.ToInt,
        out: None = None,
        *,
        explicit: bool = False,
    ) -> coo_array[ST, tuple[int]]: ...
    @overload  # spmatrix, axis: int, out: None = ...
    def nanmax[ST: _Scalar](  # type: ignore[misc]
        self: spmatrix[ST],  # zuban: ignore[misc]
        /,
        axis: onp.ToInt,
        out: None = None,
        *,
        explicit: bool = False,
    ) -> coo_matrix[ST]: ...
    #
    @overload  # axis: None = ..., out: None = ...
    def min(self, /, axis: None = None, out: None = None, *, explicit: bool = False) -> _ScalarT_co: ...
    @overload  # 1-d, axis: int, out: None = ...
    def min[ST: _Scalar](
        self: _minmax_mixin[ST, tuple[int]], /, axis: onp.ToInt | None = None, out: None = None, *, explicit: bool = False
    ) -> ST: ...
    @overload  # sparray, axis: int, out: None = ...
    def min[ST: _Scalar](  # type: ignore[misc]
        self: sparray[ST],  # zuban: ignore[misc]
        /,
        axis: onp.ToInt,
        out: None = None,
        *,
        explicit: bool = False,
    ) -> coo_array[ST, tuple[int]]: ...
    @overload  # spmatrix, axis: int, out: None = ...
    def min[ST: _Scalar](  # type: ignore[misc]
        self: spmatrix[ST],  # zuban: ignore[misc]
        /,
        axis: onp.ToInt,
        out: None = None,
        *,
        explicit: bool = False,
    ) -> coo_matrix[ST]: ...
    #
    @overload  # axis: None = ..., out: None = ...
    def nanmin(self, /, axis: None = None, out: None = None, *, explicit: bool = False) -> _ScalarT_co: ...
    @overload  # 1-d, axis: int, out: None = ...
    def nanmin[ST: _Scalar](
        self: _minmax_mixin[ST, tuple[int]], /, axis: onp.ToInt | None = None, out: None = None, *, explicit: bool = False
    ) -> ST: ...
    @overload  # sparray, axis: int, out: None = ...
    def nanmin[ST: _Scalar](  # type: ignore[misc]
        self: sparray[ST],  # zuban: ignore[misc]
        /,
        axis: onp.ToInt,
        out: None = None,
        *,
        explicit: bool = False,
    ) -> coo_array[ST, tuple[int]]: ...
    @overload  # spmatrix, axis: int, out: None = ...
    def nanmin[ST: _Scalar](  # type: ignore[misc]
        self: spmatrix[ST],  # zuban: ignore[misc]
        /,
        axis: onp.ToInt,
        out: None = None,
        *,
        explicit: bool = False,
    ) -> coo_matrix[ST]: ...

    # NOTE: The following 2 methods have identical signatures
    @overload  # axis: None = ..., out: None = ...
    def argmax(self, /, axis: None = None, out: None = None, *, explicit: bool = False) -> int: ...
    @overload  # 1-d, axis: int, out: None = ...
    def argmax(
        self: _minmax_mixin[Any, tuple[int]], /, axis: onp.ToInt | None = None, out: None = None, *, explicit: bool = False
    ) -> int: ...
    @overload  # sparray, axis: int, out: None = ...
    def argmax(self: sparray, /, axis: onp.ToInt, out: None = None, *, explicit: bool = False) -> onp.Array1D[np.intp]: ...  # type: ignore[misc]
    @overload  # spmatrix, axis: int, out: None = ...
    def argmax(self: spmatrix, /, axis: onp.ToInt, out: None = None, *, explicit: bool = False) -> onp.Matrix[np.intp]: ...  # type: ignore[misc]

    #
    @overload  # axis: None = ..., out: None = ...
    def argmin(self, /, axis: None = None, out: None = None, *, explicit: bool = False) -> int: ...
    @overload  # 1-d, axis: int, out: None = ...
    def argmin(
        self: _minmax_mixin[Any, tuple[int]], /, axis: onp.ToInt | None = None, out: None = None, *, explicit: bool = False
    ) -> int: ...
    @overload  # sparray, axis: int, out: None = ...
    def argmin(self: sparray, /, axis: onp.ToInt, out: None = None, *, explicit: bool = False) -> onp.Array1D[np.intp]: ...  # type: ignore[misc]
    @overload  # spmatrix, axis: int, out: None = ...
    def argmin(self: spmatrix, /, axis: onp.ToInt, out: None = None, *, explicit: bool = False) -> onp.Matrix[np.intp]: ...  # type: ignore[misc]
