class Nolan:
    def __init__(self, /, alpha: float | int | bool, beta: float | int | bool, x0: float | int | bool) -> None: ...
    def g(self, /, theta: float | int | bool) -> float | int | bool: ...
    @property
    def zeta(self, /) -> float | int | bool: ...
    @property
    def xi(self, /) -> float | int | bool: ...
    @property
    def c1(self, /) -> float | int | bool: ...
    @property
    def c2(self, /) -> float | int | bool: ...
    @property
    def c3(self, /) -> float | int | bool: ...

def __setstate_cython__(self: object, pyx_state: object, /) -> None: ...
def __reduce_cython__(self: object) -> None: ...
