from typing import assert_type

import numpy as np
import optype.numpy as onp

from scipy import constants

u64_nd: onp.ArrayND[np.uint64]
f32_nd: onp.ArrayND[np.float32]
f64_nd: onp.ArrayND[np.float64]
c64_nd: onp.ArrayND[np.complex64]

assert_type(constants.convert_temperature(1, "Celsius", "Kelvin"), np.float64)
assert_type(constants.convert_temperature([1], "Celsius", "Kelvin"), onp.ArrayND[np.float64])
assert_type(constants.convert_temperature(u64_nd, "Celsius", "Kelvin"), onp.ArrayND[np.float64])
assert_type(constants.convert_temperature(f32_nd, "Celsius", "Kelvin"), onp.ArrayND[np.float32])
assert_type(constants.convert_temperature(f64_nd, "Celsius", "Kelvin"), onp.ArrayND[np.float64])
assert_type(constants.convert_temperature(c64_nd, "Celsius", "Kelvin"), onp.ArrayND[np.complex64])

assert_type(constants.lambda2nu(1), np.float64)
assert_type(constants.lambda2nu([1]), onp.ArrayND[np.float64])
assert_type(constants.lambda2nu(u64_nd), onp.ArrayND[np.float64])
assert_type(constants.lambda2nu(f32_nd), onp.ArrayND[np.float32])
assert_type(constants.lambda2nu(f64_nd), onp.ArrayND[np.float64])
assert_type(constants.lambda2nu(c64_nd), onp.ArrayND[np.complex64])

assert_type(constants.nu2lambda(1), np.float64)
assert_type(constants.nu2lambda([1]), onp.ArrayND[np.float64])
assert_type(constants.nu2lambda(u64_nd), onp.ArrayND[np.float64])
assert_type(constants.nu2lambda(f32_nd), onp.ArrayND[np.float32])
assert_type(constants.nu2lambda(f64_nd), onp.ArrayND[np.float64])
assert_type(constants.nu2lambda(c64_nd), onp.ArrayND[np.complex64])

###

# The following code generates type assertions for all constants in `scipy.constants`:
#
# >>> for name in scipy.constants.__all__:
# ...     val = getattr(scipy.constants, name)
# ...     if isinstance(val, int | float):
# ...         tp = type(val).__name__
# ...         print(f"assert_type(constants.{name}.__class__, type[{tp}])")

assert_type(constants.Avogadro.__class__, type[float])
assert_type(constants.Boltzmann.__class__, type[float])
assert_type(constants.Btu.__class__, type[float])
assert_type(constants.Btu_IT.__class__, type[float])
assert_type(constants.Btu_th.__class__, type[float])
assert_type(constants.G.__class__, type[float])
assert_type(constants.Julian_year.__class__, type[float])
assert_type(constants.N_A.__class__, type[float])
assert_type(constants.Planck.__class__, type[float])
assert_type(constants.R.__class__, type[float])
assert_type(constants.Rydberg.__class__, type[float])
assert_type(constants.Stefan_Boltzmann.__class__, type[float])
assert_type(constants.Wien.__class__, type[float])
assert_type(constants.acre.__class__, type[float])
assert_type(constants.alpha.__class__, type[float])
assert_type(constants.angstrom.__class__, type[float])
assert_type(constants.arcmin.__class__, type[float])
assert_type(constants.arcminute.__class__, type[float])
assert_type(constants.arcsec.__class__, type[float])
assert_type(constants.arcsecond.__class__, type[float])
assert_type(constants.astronomical_unit.__class__, type[float])
assert_type(constants.atm.__class__, type[float])
assert_type(constants.atmosphere.__class__, type[float])
assert_type(constants.atomic_mass.__class__, type[float])
assert_type(constants.atto.__class__, type[float])
assert_type(constants.au.__class__, type[float])
assert_type(constants.bar.__class__, type[float])
assert_type(constants.barrel.__class__, type[float])
assert_type(constants.bbl.__class__, type[float])
assert_type(constants.blob.__class__, type[float])
assert_type(constants.c.__class__, type[float])
assert_type(constants.calorie.__class__, type[float])
assert_type(constants.calorie_IT.__class__, type[float])
assert_type(constants.calorie_th.__class__, type[float])
assert_type(constants.carat.__class__, type[float])
assert_type(constants.centi.__class__, type[float])
assert_type(constants.day.__class__, type[float])
assert_type(constants.deci.__class__, type[float])
assert_type(constants.degree.__class__, type[float])
assert_type(constants.degree_Fahrenheit.__class__, type[float])
assert_type(constants.deka.__class__, type[float])
assert_type(constants.dyn.__class__, type[float])
assert_type(constants.dyne.__class__, type[float])
assert_type(constants.e.__class__, type[float])
assert_type(constants.eV.__class__, type[float])
assert_type(constants.electron_mass.__class__, type[float])
assert_type(constants.electron_volt.__class__, type[float])
assert_type(constants.elementary_charge.__class__, type[float])
assert_type(constants.epsilon_0.__class__, type[float])
assert_type(constants.erg.__class__, type[float])
assert_type(constants.exa.__class__, type[float])
assert_type(constants.exbi.__class__, type[int])
assert_type(constants.femto.__class__, type[float])
assert_type(constants.fermi.__class__, type[float])
assert_type(constants.fine_structure.__class__, type[float])
assert_type(constants.fluid_ounce.__class__, type[float])
assert_type(constants.fluid_ounce_US.__class__, type[float])
assert_type(constants.fluid_ounce_imp.__class__, type[float])
assert_type(constants.foot.__class__, type[float])
assert_type(constants.g.__class__, type[float])
assert_type(constants.gallon.__class__, type[float])
assert_type(constants.gallon_US.__class__, type[float])
assert_type(constants.gallon_imp.__class__, type[float])
assert_type(constants.gas_constant.__class__, type[float])
assert_type(constants.gibi.__class__, type[int])
assert_type(constants.giga.__class__, type[float])
assert_type(constants.golden.__class__, type[float])
assert_type(constants.golden_ratio.__class__, type[float])
assert_type(constants.grain.__class__, type[float])
assert_type(constants.gram.__class__, type[float])
assert_type(constants.gravitational_constant.__class__, type[float])
assert_type(constants.h.__class__, type[float])
assert_type(constants.hbar.__class__, type[float])
assert_type(constants.hectare.__class__, type[float])
assert_type(constants.hecto.__class__, type[float])
assert_type(constants.horsepower.__class__, type[float])
assert_type(constants.hour.__class__, type[float])
assert_type(constants.hp.__class__, type[float])
assert_type(constants.inch.__class__, type[float])
assert_type(constants.k.__class__, type[float])
assert_type(constants.kgf.__class__, type[float])
assert_type(constants.kibi.__class__, type[int])
assert_type(constants.kilo.__class__, type[float])
assert_type(constants.kilogram_force.__class__, type[float])
assert_type(constants.kmh.__class__, type[float])
assert_type(constants.knot.__class__, type[float])
assert_type(constants.lb.__class__, type[float])
assert_type(constants.lbf.__class__, type[float])
assert_type(constants.light_year.__class__, type[float])
assert_type(constants.liter.__class__, type[float])
assert_type(constants.litre.__class__, type[float])
assert_type(constants.long_ton.__class__, type[float])
assert_type(constants.m_e.__class__, type[float])
assert_type(constants.m_n.__class__, type[float])
assert_type(constants.m_p.__class__, type[float])
assert_type(constants.m_u.__class__, type[float])
assert_type(constants.mach.__class__, type[float])
assert_type(constants.mebi.__class__, type[int])
assert_type(constants.mega.__class__, type[float])
assert_type(constants.metric_ton.__class__, type[float])
assert_type(constants.micro.__class__, type[float])
assert_type(constants.micron.__class__, type[float])
assert_type(constants.mil.__class__, type[float])
assert_type(constants.mile.__class__, type[float])
assert_type(constants.milli.__class__, type[float])
assert_type(constants.minute.__class__, type[float])
assert_type(constants.mmHg.__class__, type[float])
assert_type(constants.mph.__class__, type[float])
assert_type(constants.mu_0.__class__, type[float])
assert_type(constants.nano.__class__, type[float])
assert_type(constants.nautical_mile.__class__, type[float])
assert_type(constants.neutron_mass.__class__, type[float])
assert_type(constants.ounce.__class__, type[float])
assert_type(constants.oz.__class__, type[float])
assert_type(constants.parsec.__class__, type[float])
assert_type(constants.pebi.__class__, type[int])
assert_type(constants.peta.__class__, type[float])
assert_type(constants.pi.__class__, type[float])
assert_type(constants.pico.__class__, type[float])
assert_type(constants.point.__class__, type[float])
assert_type(constants.pound.__class__, type[float])
assert_type(constants.pound_force.__class__, type[float])
assert_type(constants.proton_mass.__class__, type[float])
assert_type(constants.psi.__class__, type[float])
assert_type(constants.pt.__class__, type[float])
assert_type(constants.quecto.__class__, type[float])
assert_type(constants.quetta.__class__, type[float])
assert_type(constants.ronna.__class__, type[float])
assert_type(constants.ronto.__class__, type[float])
assert_type(constants.short_ton.__class__, type[float])
assert_type(constants.sigma.__class__, type[float])
assert_type(constants.slinch.__class__, type[float])
assert_type(constants.slug.__class__, type[float])
assert_type(constants.speed_of_light.__class__, type[float])
assert_type(constants.speed_of_sound.__class__, type[float])
assert_type(constants.stone.__class__, type[float])
assert_type(constants.survey_foot.__class__, type[float])
assert_type(constants.survey_mile.__class__, type[float])
assert_type(constants.tebi.__class__, type[int])
assert_type(constants.tera.__class__, type[float])
assert_type(constants.ton_TNT.__class__, type[float])
assert_type(constants.torr.__class__, type[float])
assert_type(constants.troy_ounce.__class__, type[float])
assert_type(constants.troy_pound.__class__, type[float])
assert_type(constants.u.__class__, type[float])
assert_type(constants.week.__class__, type[float])
assert_type(constants.yard.__class__, type[float])
assert_type(constants.year.__class__, type[float])
assert_type(constants.yobi.__class__, type[int])
assert_type(constants.yocto.__class__, type[float])
assert_type(constants.yotta.__class__, type[float])
assert_type(constants.zebi.__class__, type[int])
assert_type(constants.zepto.__class__, type[float])
assert_type(constants.zero_Celsius.__class__, type[float])
assert_type(constants.zetta.__class__, type[float])
