name: Build a new release, and publish to PyPI

on:
  workflow_dispatch:
  release:
    types: [created]

env:
  UV_LOCKED: 1

jobs:
  pypi-publish:
    name: Publish release to PyPI
    runs-on: ubuntu-latest
    timeout-minutes: 5
    environment:
      name: pypi
      url: https://pypi.org/p/scipy-stubs
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v6
        with:
          python-version: "3.13"

      - name: uv build
        run: uv build

      - name: publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
