name: Update test coverage

permissions: {}

on:
  push:
    branches: [master]
    paths:
      - tests/**
      - scripts/test_coverage.py
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  update-coverage:
    name: update-coverage
    runs-on: ubuntu-latest
    timeout-minutes: 5

    permissions:
      contents: read # to check out the repository
      issues: write # to update the body of the test coverage tracking issue

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - uses: astral-sh/setup-uv@11f9893b081a58869d3b5fccaea48c9e9e46f990 # v8.3.2

      - name: generate coverage report
        run: uv run scripts/test_coverage.py > .coverage.md

      - name: "update issue #1099"
        run: gh issue edit 1099 --repo scipy/scipy-stubs --body-file .coverage.md
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
